// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Experimental: the backing management API is currently enabled only in Logfire staging environments. Manages one active token for a Logfire frontend application. Rotate in two applies with two resource blocks: add the replacement and deploy its `token`, then remove the old resource to revoke it. The provider never revokes an old token while creating a new one. Token issuance is not retried automatically because the operation is not idempotent; after an uncertain failure, list the application's tokens and adopt the one unambiguous new active token. Before destroying the whole application tree, set the last token's `revokeOnDestroy` to `false` in a separate apply; application deletion then revokes every attached token.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pydantic/pulumi-logfire/sdk/go/logfire"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := logfire.NewFrontendApplicationToken(ctx, "current", &logfire.FrontendApplicationTokenArgs{
//				ProjectId:     pulumi.Any(logfire_frontend_application.Browser.Project_id),
//				ApplicationId: pulumi.Any(logfire_frontend_application.Browser.Id),
//				AdoptTokenId:  pulumi.Any(logfire_frontend_application.Browser.Token_id),
//			})
//			if err != nil {
//				return err
//			}
//			// First apply with both resources. Deploy the replacement output everywhere.
//			// Then remove `current` and apply again to revoke the previous token.
//			replacement, err := logfire.NewFrontendApplicationToken(ctx, "replacement", &logfire.FrontendApplicationTokenArgs{
//				ProjectId:       pulumi.Any(logfire_frontend_application.Browser.Project_id),
//				ApplicationId:   pulumi.Any(logfire_frontend_application.Browser.Id),
//				RevokeOnDestroy: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("rotatedBrowserWriteToken", replacement.Token)
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// ```sh
// $ pulumi import logfire:index/frontendApplicationToken:FrontendApplicationToken current "project-id/application-id/token-id"
// ```
type FrontendApplicationToken struct {
	pulumi.CustomResourceState

	// Existing active token to adopt instead of issuing another. Use the application's `tokenId` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
	AdoptTokenId pulumi.StringPtrOutput `pulumi:"adoptTokenId"`
	// UUID of the frontend application.
	ApplicationId pulumi.StringOutput `pulumi:"applicationId"`
	// Timestamp when the token was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Timestamp when the token was last used, when known.
	LastUsedAt pulumi.StringOutput `pulumi:"lastUsedAt"`
	// UUID of the project that owns the application.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
	RevokeOnDestroy pulumi.BoolOutput `pulumi:"revokeOnDestroy"`
	// Token status. A managed token remains in state only while active.
	Status pulumi.StringOutput `pulumi:"status"`
	// Active restricted browser token. The provider recovers this value on refresh and import.
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewFrontendApplicationToken registers a new resource with the given unique name, arguments, and options.
func NewFrontendApplicationToken(ctx *pulumi.Context,
	name string, args *FrontendApplicationTokenArgs, opts ...pulumi.ResourceOption) (*FrontendApplicationToken, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApplicationId == nil {
		return nil, errors.New("invalid value for required argument 'ApplicationId'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FrontendApplicationToken
	err := ctx.RegisterResource("logfire:index/frontendApplicationToken:FrontendApplicationToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFrontendApplicationToken gets an existing FrontendApplicationToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFrontendApplicationToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FrontendApplicationTokenState, opts ...pulumi.ResourceOption) (*FrontendApplicationToken, error) {
	var resource FrontendApplicationToken
	err := ctx.ReadResource("logfire:index/frontendApplicationToken:FrontendApplicationToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FrontendApplicationToken resources.
type frontendApplicationTokenState struct {
	// Existing active token to adopt instead of issuing another. Use the application's `tokenId` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
	AdoptTokenId *string `pulumi:"adoptTokenId"`
	// UUID of the frontend application.
	ApplicationId *string `pulumi:"applicationId"`
	// Timestamp when the token was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Timestamp when the token was last used, when known.
	LastUsedAt *string `pulumi:"lastUsedAt"`
	// UUID of the project that owns the application.
	ProjectId *string `pulumi:"projectId"`
	// Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
	RevokeOnDestroy *bool `pulumi:"revokeOnDestroy"`
	// Token status. A managed token remains in state only while active.
	Status *string `pulumi:"status"`
	// Active restricted browser token. The provider recovers this value on refresh and import.
	Token *string `pulumi:"token"`
}

type FrontendApplicationTokenState struct {
	// Existing active token to adopt instead of issuing another. Use the application's `tokenId` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
	AdoptTokenId pulumi.StringPtrInput
	// UUID of the frontend application.
	ApplicationId pulumi.StringPtrInput
	// Timestamp when the token was created.
	CreatedAt pulumi.StringPtrInput
	// Timestamp when the token was last used, when known.
	LastUsedAt pulumi.StringPtrInput
	// UUID of the project that owns the application.
	ProjectId pulumi.StringPtrInput
	// Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
	RevokeOnDestroy pulumi.BoolPtrInput
	// Token status. A managed token remains in state only while active.
	Status pulumi.StringPtrInput
	// Active restricted browser token. The provider recovers this value on refresh and import.
	Token pulumi.StringPtrInput
}

func (FrontendApplicationTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*frontendApplicationTokenState)(nil)).Elem()
}

type frontendApplicationTokenArgs struct {
	// Existing active token to adopt instead of issuing another. Use the application's `tokenId` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
	AdoptTokenId *string `pulumi:"adoptTokenId"`
	// UUID of the frontend application.
	ApplicationId string `pulumi:"applicationId"`
	// UUID of the project that owns the application.
	ProjectId string `pulumi:"projectId"`
	// Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
	RevokeOnDestroy *bool `pulumi:"revokeOnDestroy"`
}

// The set of arguments for constructing a FrontendApplicationToken resource.
type FrontendApplicationTokenArgs struct {
	// Existing active token to adopt instead of issuing another. Use the application's `tokenId` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
	AdoptTokenId pulumi.StringPtrInput
	// UUID of the frontend application.
	ApplicationId pulumi.StringInput
	// UUID of the project that owns the application.
	ProjectId pulumi.StringInput
	// Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
	RevokeOnDestroy pulumi.BoolPtrInput
}

func (FrontendApplicationTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*frontendApplicationTokenArgs)(nil)).Elem()
}

type FrontendApplicationTokenInput interface {
	pulumi.Input

	ToFrontendApplicationTokenOutput() FrontendApplicationTokenOutput
	ToFrontendApplicationTokenOutputWithContext(ctx context.Context) FrontendApplicationTokenOutput
}

func (*FrontendApplicationToken) ElementType() reflect.Type {
	return reflect.TypeOf((**FrontendApplicationToken)(nil)).Elem()
}

func (i *FrontendApplicationToken) ToFrontendApplicationTokenOutput() FrontendApplicationTokenOutput {
	return i.ToFrontendApplicationTokenOutputWithContext(context.Background())
}

func (i *FrontendApplicationToken) ToFrontendApplicationTokenOutputWithContext(ctx context.Context) FrontendApplicationTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FrontendApplicationTokenOutput)
}

// FrontendApplicationTokenArrayInput is an input type that accepts FrontendApplicationTokenArray and FrontendApplicationTokenArrayOutput values.
// You can construct a concrete instance of `FrontendApplicationTokenArrayInput` via:
//
//	FrontendApplicationTokenArray{ FrontendApplicationTokenArgs{...} }
type FrontendApplicationTokenArrayInput interface {
	pulumi.Input

	ToFrontendApplicationTokenArrayOutput() FrontendApplicationTokenArrayOutput
	ToFrontendApplicationTokenArrayOutputWithContext(context.Context) FrontendApplicationTokenArrayOutput
}

type FrontendApplicationTokenArray []FrontendApplicationTokenInput

func (FrontendApplicationTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FrontendApplicationToken)(nil)).Elem()
}

func (i FrontendApplicationTokenArray) ToFrontendApplicationTokenArrayOutput() FrontendApplicationTokenArrayOutput {
	return i.ToFrontendApplicationTokenArrayOutputWithContext(context.Background())
}

func (i FrontendApplicationTokenArray) ToFrontendApplicationTokenArrayOutputWithContext(ctx context.Context) FrontendApplicationTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FrontendApplicationTokenArrayOutput)
}

// FrontendApplicationTokenMapInput is an input type that accepts FrontendApplicationTokenMap and FrontendApplicationTokenMapOutput values.
// You can construct a concrete instance of `FrontendApplicationTokenMapInput` via:
//
//	FrontendApplicationTokenMap{ "key": FrontendApplicationTokenArgs{...} }
type FrontendApplicationTokenMapInput interface {
	pulumi.Input

	ToFrontendApplicationTokenMapOutput() FrontendApplicationTokenMapOutput
	ToFrontendApplicationTokenMapOutputWithContext(context.Context) FrontendApplicationTokenMapOutput
}

type FrontendApplicationTokenMap map[string]FrontendApplicationTokenInput

func (FrontendApplicationTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FrontendApplicationToken)(nil)).Elem()
}

func (i FrontendApplicationTokenMap) ToFrontendApplicationTokenMapOutput() FrontendApplicationTokenMapOutput {
	return i.ToFrontendApplicationTokenMapOutputWithContext(context.Background())
}

func (i FrontendApplicationTokenMap) ToFrontendApplicationTokenMapOutputWithContext(ctx context.Context) FrontendApplicationTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FrontendApplicationTokenMapOutput)
}

type FrontendApplicationTokenOutput struct{ *pulumi.OutputState }

func (FrontendApplicationTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FrontendApplicationToken)(nil)).Elem()
}

func (o FrontendApplicationTokenOutput) ToFrontendApplicationTokenOutput() FrontendApplicationTokenOutput {
	return o
}

func (o FrontendApplicationTokenOutput) ToFrontendApplicationTokenOutputWithContext(ctx context.Context) FrontendApplicationTokenOutput {
	return o
}

// Existing active token to adopt instead of issuing another. Use the application's `tokenId` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
func (o FrontendApplicationTokenOutput) AdoptTokenId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringPtrOutput { return v.AdoptTokenId }).(pulumi.StringPtrOutput)
}

// UUID of the frontend application.
func (o FrontendApplicationTokenOutput) ApplicationId() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringOutput { return v.ApplicationId }).(pulumi.StringOutput)
}

// Timestamp when the token was created.
func (o FrontendApplicationTokenOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Timestamp when the token was last used, when known.
func (o FrontendApplicationTokenOutput) LastUsedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringOutput { return v.LastUsedAt }).(pulumi.StringOutput)
}

// UUID of the project that owns the application.
func (o FrontendApplicationTokenOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
func (o FrontendApplicationTokenOutput) RevokeOnDestroy() pulumi.BoolOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.BoolOutput { return v.RevokeOnDestroy }).(pulumi.BoolOutput)
}

// Token status. A managed token remains in state only while active.
func (o FrontendApplicationTokenOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Active restricted browser token. The provider recovers this value on refresh and import.
func (o FrontendApplicationTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplicationToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

type FrontendApplicationTokenArrayOutput struct{ *pulumi.OutputState }

func (FrontendApplicationTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FrontendApplicationToken)(nil)).Elem()
}

func (o FrontendApplicationTokenArrayOutput) ToFrontendApplicationTokenArrayOutput() FrontendApplicationTokenArrayOutput {
	return o
}

func (o FrontendApplicationTokenArrayOutput) ToFrontendApplicationTokenArrayOutputWithContext(ctx context.Context) FrontendApplicationTokenArrayOutput {
	return o
}

func (o FrontendApplicationTokenArrayOutput) Index(i pulumi.IntInput) FrontendApplicationTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FrontendApplicationToken {
		return vs[0].([]*FrontendApplicationToken)[vs[1].(int)]
	}).(FrontendApplicationTokenOutput)
}

type FrontendApplicationTokenMapOutput struct{ *pulumi.OutputState }

func (FrontendApplicationTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FrontendApplicationToken)(nil)).Elem()
}

func (o FrontendApplicationTokenMapOutput) ToFrontendApplicationTokenMapOutput() FrontendApplicationTokenMapOutput {
	return o
}

func (o FrontendApplicationTokenMapOutput) ToFrontendApplicationTokenMapOutputWithContext(ctx context.Context) FrontendApplicationTokenMapOutput {
	return o
}

func (o FrontendApplicationTokenMapOutput) MapIndex(k pulumi.StringInput) FrontendApplicationTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FrontendApplicationToken {
		return vs[0].(map[string]*FrontendApplicationToken)[vs[1].(string)]
	}).(FrontendApplicationTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FrontendApplicationTokenInput)(nil)).Elem(), &FrontendApplicationToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*FrontendApplicationTokenArrayInput)(nil)).Elem(), FrontendApplicationTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FrontendApplicationTokenMapInput)(nil)).Elem(), FrontendApplicationTokenMap{})
	pulumi.RegisterOutputType(FrontendApplicationTokenOutput{})
	pulumi.RegisterOutputType(FrontendApplicationTokenArrayOutput{})
	pulumi.RegisterOutputType(FrontendApplicationTokenMapOutput{})
}
