// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Experimental: the backing management API is currently enabled only in Logfire staging environments. Manages an immutable Logfire frontend application identity and exposes one active restricted browser token. Use `FrontendApplicationToken` for two-phase rotation. Creation is not retried automatically because the operation is not idempotent; after an uncertain failure, list the applications and import the matching identity instead of applying again.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pydantic/pulumi-logfire/sdk/go/logfire"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := logfire.NewProject(ctx, "example", nil)
//			if err != nil {
//				return err
//			}
//			browser, err := logfire.NewFrontendApplication(ctx, "browser", &logfire.FrontendApplicationArgs{
//				ProjectId:        example.ID(),
//				ServiceNamespace: pulumi.String("storefront"),
//				Environment:      pulumi.String("production"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("browserWriteToken", browser.Token)
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// ```sh
// $ pulumi import logfire:index/frontendApplication:FrontendApplication browser "project-id/application-id"
// ```
type FrontendApplication struct {
	pulumi.CustomResourceState

	// Allow creation when telemetry already reports under `name`. Set this before replacing `serviceNamespace` or `environment` without changing `name`.
	AdoptExistingServiceName pulumi.BoolPtrOutput `pulumi:"adoptExistingServiceName"`
	// Timestamp when the application was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Immutable value used to overwrite `deployment.environment.name` when set.
	Environment pulumi.StringPtrOutput `pulumi:"environment"`
	// Immutable application name. Logfire overwrites `service.name` with this value.
	Name pulumi.StringOutput `pulumi:"name"`
	// UUID of the project that owns the application.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Immutable value used to overwrite `service.namespace` when set.
	ServiceNamespace pulumi.StringPtrOutput `pulumi:"serviceNamespace"`
	// An active restricted browser token. The provider recovers this value on refresh and import.
	Token pulumi.StringOutput `pulumi:"token"`
	// Identifier of an active restricted browser token.
	TokenId pulumi.StringOutput `pulumi:"tokenId"`
}

// NewFrontendApplication registers a new resource with the given unique name, arguments, and options.
func NewFrontendApplication(ctx *pulumi.Context,
	name string, args *FrontendApplicationArgs, opts ...pulumi.ResourceOption) (*FrontendApplication, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FrontendApplication
	err := ctx.RegisterResource("logfire:index/frontendApplication:FrontendApplication", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFrontendApplication gets an existing FrontendApplication resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFrontendApplication(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FrontendApplicationState, opts ...pulumi.ResourceOption) (*FrontendApplication, error) {
	var resource FrontendApplication
	err := ctx.ReadResource("logfire:index/frontendApplication:FrontendApplication", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FrontendApplication resources.
type frontendApplicationState struct {
	// Allow creation when telemetry already reports under `name`. Set this before replacing `serviceNamespace` or `environment` without changing `name`.
	AdoptExistingServiceName *bool `pulumi:"adoptExistingServiceName"`
	// Timestamp when the application was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Immutable value used to overwrite `deployment.environment.name` when set.
	Environment *string `pulumi:"environment"`
	// Immutable application name. Logfire overwrites `service.name` with this value.
	Name *string `pulumi:"name"`
	// UUID of the project that owns the application.
	ProjectId *string `pulumi:"projectId"`
	// Immutable value used to overwrite `service.namespace` when set.
	ServiceNamespace *string `pulumi:"serviceNamespace"`
	// An active restricted browser token. The provider recovers this value on refresh and import.
	Token *string `pulumi:"token"`
	// Identifier of an active restricted browser token.
	TokenId *string `pulumi:"tokenId"`
}

type FrontendApplicationState struct {
	// Allow creation when telemetry already reports under `name`. Set this before replacing `serviceNamespace` or `environment` without changing `name`.
	AdoptExistingServiceName pulumi.BoolPtrInput
	// Timestamp when the application was created.
	CreatedAt pulumi.StringPtrInput
	// Immutable value used to overwrite `deployment.environment.name` when set.
	Environment pulumi.StringPtrInput
	// Immutable application name. Logfire overwrites `service.name` with this value.
	Name pulumi.StringPtrInput
	// UUID of the project that owns the application.
	ProjectId pulumi.StringPtrInput
	// Immutable value used to overwrite `service.namespace` when set.
	ServiceNamespace pulumi.StringPtrInput
	// An active restricted browser token. The provider recovers this value on refresh and import.
	Token pulumi.StringPtrInput
	// Identifier of an active restricted browser token.
	TokenId pulumi.StringPtrInput
}

func (FrontendApplicationState) ElementType() reflect.Type {
	return reflect.TypeOf((*frontendApplicationState)(nil)).Elem()
}

type frontendApplicationArgs struct {
	// Allow creation when telemetry already reports under `name`. Set this before replacing `serviceNamespace` or `environment` without changing `name`.
	AdoptExistingServiceName *bool `pulumi:"adoptExistingServiceName"`
	// Immutable value used to overwrite `deployment.environment.name` when set.
	Environment *string `pulumi:"environment"`
	// Immutable application name. Logfire overwrites `service.name` with this value.
	Name *string `pulumi:"name"`
	// UUID of the project that owns the application.
	ProjectId string `pulumi:"projectId"`
	// Immutable value used to overwrite `service.namespace` when set.
	ServiceNamespace *string `pulumi:"serviceNamespace"`
}

// The set of arguments for constructing a FrontendApplication resource.
type FrontendApplicationArgs struct {
	// Allow creation when telemetry already reports under `name`. Set this before replacing `serviceNamespace` or `environment` without changing `name`.
	AdoptExistingServiceName pulumi.BoolPtrInput
	// Immutable value used to overwrite `deployment.environment.name` when set.
	Environment pulumi.StringPtrInput
	// Immutable application name. Logfire overwrites `service.name` with this value.
	Name pulumi.StringPtrInput
	// UUID of the project that owns the application.
	ProjectId pulumi.StringInput
	// Immutable value used to overwrite `service.namespace` when set.
	ServiceNamespace pulumi.StringPtrInput
}

func (FrontendApplicationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*frontendApplicationArgs)(nil)).Elem()
}

type FrontendApplicationInput interface {
	pulumi.Input

	ToFrontendApplicationOutput() FrontendApplicationOutput
	ToFrontendApplicationOutputWithContext(ctx context.Context) FrontendApplicationOutput
}

func (*FrontendApplication) ElementType() reflect.Type {
	return reflect.TypeOf((**FrontendApplication)(nil)).Elem()
}

func (i *FrontendApplication) ToFrontendApplicationOutput() FrontendApplicationOutput {
	return i.ToFrontendApplicationOutputWithContext(context.Background())
}

func (i *FrontendApplication) ToFrontendApplicationOutputWithContext(ctx context.Context) FrontendApplicationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FrontendApplicationOutput)
}

// FrontendApplicationArrayInput is an input type that accepts FrontendApplicationArray and FrontendApplicationArrayOutput values.
// You can construct a concrete instance of `FrontendApplicationArrayInput` via:
//
//	FrontendApplicationArray{ FrontendApplicationArgs{...} }
type FrontendApplicationArrayInput interface {
	pulumi.Input

	ToFrontendApplicationArrayOutput() FrontendApplicationArrayOutput
	ToFrontendApplicationArrayOutputWithContext(context.Context) FrontendApplicationArrayOutput
}

type FrontendApplicationArray []FrontendApplicationInput

func (FrontendApplicationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FrontendApplication)(nil)).Elem()
}

func (i FrontendApplicationArray) ToFrontendApplicationArrayOutput() FrontendApplicationArrayOutput {
	return i.ToFrontendApplicationArrayOutputWithContext(context.Background())
}

func (i FrontendApplicationArray) ToFrontendApplicationArrayOutputWithContext(ctx context.Context) FrontendApplicationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FrontendApplicationArrayOutput)
}

// FrontendApplicationMapInput is an input type that accepts FrontendApplicationMap and FrontendApplicationMapOutput values.
// You can construct a concrete instance of `FrontendApplicationMapInput` via:
//
//	FrontendApplicationMap{ "key": FrontendApplicationArgs{...} }
type FrontendApplicationMapInput interface {
	pulumi.Input

	ToFrontendApplicationMapOutput() FrontendApplicationMapOutput
	ToFrontendApplicationMapOutputWithContext(context.Context) FrontendApplicationMapOutput
}

type FrontendApplicationMap map[string]FrontendApplicationInput

func (FrontendApplicationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FrontendApplication)(nil)).Elem()
}

func (i FrontendApplicationMap) ToFrontendApplicationMapOutput() FrontendApplicationMapOutput {
	return i.ToFrontendApplicationMapOutputWithContext(context.Background())
}

func (i FrontendApplicationMap) ToFrontendApplicationMapOutputWithContext(ctx context.Context) FrontendApplicationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FrontendApplicationMapOutput)
}

type FrontendApplicationOutput struct{ *pulumi.OutputState }

func (FrontendApplicationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FrontendApplication)(nil)).Elem()
}

func (o FrontendApplicationOutput) ToFrontendApplicationOutput() FrontendApplicationOutput {
	return o
}

func (o FrontendApplicationOutput) ToFrontendApplicationOutputWithContext(ctx context.Context) FrontendApplicationOutput {
	return o
}

// Allow creation when telemetry already reports under `name`. Set this before replacing `serviceNamespace` or `environment` without changing `name`.
func (o FrontendApplicationOutput) AdoptExistingServiceName() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.BoolPtrOutput { return v.AdoptExistingServiceName }).(pulumi.BoolPtrOutput)
}

// Timestamp when the application was created.
func (o FrontendApplicationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Immutable value used to overwrite `deployment.environment.name` when set.
func (o FrontendApplicationOutput) Environment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringPtrOutput { return v.Environment }).(pulumi.StringPtrOutput)
}

// Immutable application name. Logfire overwrites `service.name` with this value.
func (o FrontendApplicationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// UUID of the project that owns the application.
func (o FrontendApplicationOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Immutable value used to overwrite `service.namespace` when set.
func (o FrontendApplicationOutput) ServiceNamespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringPtrOutput { return v.ServiceNamespace }).(pulumi.StringPtrOutput)
}

// An active restricted browser token. The provider recovers this value on refresh and import.
func (o FrontendApplicationOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// Identifier of an active restricted browser token.
func (o FrontendApplicationOutput) TokenId() pulumi.StringOutput {
	return o.ApplyT(func(v *FrontendApplication) pulumi.StringOutput { return v.TokenId }).(pulumi.StringOutput)
}

type FrontendApplicationArrayOutput struct{ *pulumi.OutputState }

func (FrontendApplicationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FrontendApplication)(nil)).Elem()
}

func (o FrontendApplicationArrayOutput) ToFrontendApplicationArrayOutput() FrontendApplicationArrayOutput {
	return o
}

func (o FrontendApplicationArrayOutput) ToFrontendApplicationArrayOutputWithContext(ctx context.Context) FrontendApplicationArrayOutput {
	return o
}

func (o FrontendApplicationArrayOutput) Index(i pulumi.IntInput) FrontendApplicationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FrontendApplication {
		return vs[0].([]*FrontendApplication)[vs[1].(int)]
	}).(FrontendApplicationOutput)
}

type FrontendApplicationMapOutput struct{ *pulumi.OutputState }

func (FrontendApplicationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FrontendApplication)(nil)).Elem()
}

func (o FrontendApplicationMapOutput) ToFrontendApplicationMapOutput() FrontendApplicationMapOutput {
	return o
}

func (o FrontendApplicationMapOutput) ToFrontendApplicationMapOutputWithContext(ctx context.Context) FrontendApplicationMapOutput {
	return o
}

func (o FrontendApplicationMapOutput) MapIndex(k pulumi.StringInput) FrontendApplicationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FrontendApplication {
		return vs[0].(map[string]*FrontendApplication)[vs[1].(string)]
	}).(FrontendApplicationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FrontendApplicationInput)(nil)).Elem(), &FrontendApplication{})
	pulumi.RegisterInputType(reflect.TypeOf((*FrontendApplicationArrayInput)(nil)).Elem(), FrontendApplicationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FrontendApplicationMapInput)(nil)).Elem(), FrontendApplicationMap{})
	pulumi.RegisterOutputType(FrontendApplicationOutput{})
	pulumi.RegisterOutputType(FrontendApplicationArrayOutput{})
	pulumi.RegisterOutputType(FrontendApplicationMapOutput{})
}
