// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// ## Import
//
// Import a provider by UUID using the same organization's management token:
//
// terraform
//
// import {
//
//	to = logfire_gateway_provider.openai
//
//	id = "018f45c0-3cab-7b2f-a8f7-8a0b55a7ed11"
//
// }
//
// Or use the command line:
//
// ```sh
// $ pulumi import logfire:index/gatewayProvider:GatewayProvider openai 018f45c0-3cab-7b2f-a8f7-8a0b55a7ed11
// ```
//
// Import reads public configuration only. Set `api_key` in your configuration;
//
// the next apply writes that key to the imported provider. Import does not recover
//
// the existing secret.
type GatewayProvider struct {
	pulumi.CustomResourceState

	ApiKey pulumi.StringOutput `pulumi:"apiKey"`
	// Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
	BedrockApi pulumi.StringPtrOutput `pulumi:"bedrockApi"`
	// AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
	BedrockRegion pulumi.StringPtrOutput `pulumi:"bedrockRegion"`
	// Timestamp when the provider was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Require known model pricing before forwarding requests. Defaults to true.
	RequirePricing pulumi.BoolOutput `pulumi:"requirePricing"`
	// Organization-unique provider slug. Changing it replaces the provider.
	Slug pulumi.StringOutput `pulumi:"slug"`
	// Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
	Vendor pulumi.StringOutput `pulumi:"vendor"`
}

// NewGatewayProvider registers a new resource with the given unique name, arguments, and options.
func NewGatewayProvider(ctx *pulumi.Context,
	name string, args *GatewayProviderArgs, opts ...pulumi.ResourceOption) (*GatewayProvider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiKey == nil {
		return nil, errors.New("invalid value for required argument 'ApiKey'")
	}
	if args.Slug == nil {
		return nil, errors.New("invalid value for required argument 'Slug'")
	}
	if args.Vendor == nil {
		return nil, errors.New("invalid value for required argument 'Vendor'")
	}
	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GatewayProvider
	err := ctx.RegisterResource("logfire:index/gatewayProvider:GatewayProvider", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGatewayProvider gets an existing GatewayProvider resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGatewayProvider(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GatewayProviderState, opts ...pulumi.ResourceOption) (*GatewayProvider, error) {
	var resource GatewayProvider
	err := ctx.ReadResource("logfire:index/gatewayProvider:GatewayProvider", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GatewayProvider resources.
type gatewayProviderState struct {
	ApiKey *string `pulumi:"apiKey"`
	// Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
	BedrockApi *string `pulumi:"bedrockApi"`
	// AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
	BedrockRegion *string `pulumi:"bedrockRegion"`
	// Timestamp when the provider was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Require known model pricing before forwarding requests. Defaults to true.
	RequirePricing *bool `pulumi:"requirePricing"`
	// Organization-unique provider slug. Changing it replaces the provider.
	Slug *string `pulumi:"slug"`
	// Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
	Vendor *string `pulumi:"vendor"`
}

type GatewayProviderState struct {
	ApiKey pulumi.StringPtrInput
	// Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
	BedrockApi pulumi.StringPtrInput
	// AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
	BedrockRegion pulumi.StringPtrInput
	// Timestamp when the provider was created.
	CreatedAt pulumi.StringPtrInput
	// Require known model pricing before forwarding requests. Defaults to true.
	RequirePricing pulumi.BoolPtrInput
	// Organization-unique provider slug. Changing it replaces the provider.
	Slug pulumi.StringPtrInput
	// Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
	Vendor pulumi.StringPtrInput
}

func (GatewayProviderState) ElementType() reflect.Type {
	return reflect.TypeOf((*gatewayProviderState)(nil)).Elem()
}

type gatewayProviderArgs struct {
	ApiKey string `pulumi:"apiKey"`
	// Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
	BedrockApi *string `pulumi:"bedrockApi"`
	// AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
	BedrockRegion *string `pulumi:"bedrockRegion"`
	// Require known model pricing before forwarding requests. Defaults to true.
	RequirePricing *bool `pulumi:"requirePricing"`
	// Organization-unique provider slug. Changing it replaces the provider.
	Slug string `pulumi:"slug"`
	// Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
	Vendor string `pulumi:"vendor"`
}

// The set of arguments for constructing a GatewayProvider resource.
type GatewayProviderArgs struct {
	ApiKey pulumi.StringInput
	// Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
	BedrockApi pulumi.StringPtrInput
	// AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
	BedrockRegion pulumi.StringPtrInput
	// Require known model pricing before forwarding requests. Defaults to true.
	RequirePricing pulumi.BoolPtrInput
	// Organization-unique provider slug. Changing it replaces the provider.
	Slug pulumi.StringInput
	// Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
	Vendor pulumi.StringInput
}

func (GatewayProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gatewayProviderArgs)(nil)).Elem()
}

type GatewayProviderInput interface {
	pulumi.Input

	ToGatewayProviderOutput() GatewayProviderOutput
	ToGatewayProviderOutputWithContext(ctx context.Context) GatewayProviderOutput
}

func (*GatewayProvider) ElementType() reflect.Type {
	return reflect.TypeOf((**GatewayProvider)(nil)).Elem()
}

func (i *GatewayProvider) ToGatewayProviderOutput() GatewayProviderOutput {
	return i.ToGatewayProviderOutputWithContext(context.Background())
}

func (i *GatewayProvider) ToGatewayProviderOutputWithContext(ctx context.Context) GatewayProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GatewayProviderOutput)
}

// GatewayProviderArrayInput is an input type that accepts GatewayProviderArray and GatewayProviderArrayOutput values.
// You can construct a concrete instance of `GatewayProviderArrayInput` via:
//
//	GatewayProviderArray{ GatewayProviderArgs{...} }
type GatewayProviderArrayInput interface {
	pulumi.Input

	ToGatewayProviderArrayOutput() GatewayProviderArrayOutput
	ToGatewayProviderArrayOutputWithContext(context.Context) GatewayProviderArrayOutput
}

type GatewayProviderArray []GatewayProviderInput

func (GatewayProviderArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GatewayProvider)(nil)).Elem()
}

func (i GatewayProviderArray) ToGatewayProviderArrayOutput() GatewayProviderArrayOutput {
	return i.ToGatewayProviderArrayOutputWithContext(context.Background())
}

func (i GatewayProviderArray) ToGatewayProviderArrayOutputWithContext(ctx context.Context) GatewayProviderArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GatewayProviderArrayOutput)
}

// GatewayProviderMapInput is an input type that accepts GatewayProviderMap and GatewayProviderMapOutput values.
// You can construct a concrete instance of `GatewayProviderMapInput` via:
//
//	GatewayProviderMap{ "key": GatewayProviderArgs{...} }
type GatewayProviderMapInput interface {
	pulumi.Input

	ToGatewayProviderMapOutput() GatewayProviderMapOutput
	ToGatewayProviderMapOutputWithContext(context.Context) GatewayProviderMapOutput
}

type GatewayProviderMap map[string]GatewayProviderInput

func (GatewayProviderMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GatewayProvider)(nil)).Elem()
}

func (i GatewayProviderMap) ToGatewayProviderMapOutput() GatewayProviderMapOutput {
	return i.ToGatewayProviderMapOutputWithContext(context.Background())
}

func (i GatewayProviderMap) ToGatewayProviderMapOutputWithContext(ctx context.Context) GatewayProviderMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GatewayProviderMapOutput)
}

type GatewayProviderOutput struct{ *pulumi.OutputState }

func (GatewayProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GatewayProvider)(nil)).Elem()
}

func (o GatewayProviderOutput) ToGatewayProviderOutput() GatewayProviderOutput {
	return o
}

func (o GatewayProviderOutput) ToGatewayProviderOutputWithContext(ctx context.Context) GatewayProviderOutput {
	return o
}

func (o GatewayProviderOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.StringOutput { return v.ApiKey }).(pulumi.StringOutput)
}

// Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
func (o GatewayProviderOutput) BedrockApi() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.StringPtrOutput { return v.BedrockApi }).(pulumi.StringPtrOutput)
}

// AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
func (o GatewayProviderOutput) BedrockRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.StringPtrOutput { return v.BedrockRegion }).(pulumi.StringPtrOutput)
}

// Timestamp when the provider was created.
func (o GatewayProviderOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Require known model pricing before forwarding requests. Defaults to true.
func (o GatewayProviderOutput) RequirePricing() pulumi.BoolOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.BoolOutput { return v.RequirePricing }).(pulumi.BoolOutput)
}

// Organization-unique provider slug. Changing it replaces the provider.
func (o GatewayProviderOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.StringOutput { return v.Slug }).(pulumi.StringOutput)
}

// Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
func (o GatewayProviderOutput) Vendor() pulumi.StringOutput {
	return o.ApplyT(func(v *GatewayProvider) pulumi.StringOutput { return v.Vendor }).(pulumi.StringOutput)
}

type GatewayProviderArrayOutput struct{ *pulumi.OutputState }

func (GatewayProviderArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GatewayProvider)(nil)).Elem()
}

func (o GatewayProviderArrayOutput) ToGatewayProviderArrayOutput() GatewayProviderArrayOutput {
	return o
}

func (o GatewayProviderArrayOutput) ToGatewayProviderArrayOutputWithContext(ctx context.Context) GatewayProviderArrayOutput {
	return o
}

func (o GatewayProviderArrayOutput) Index(i pulumi.IntInput) GatewayProviderOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GatewayProvider {
		return vs[0].([]*GatewayProvider)[vs[1].(int)]
	}).(GatewayProviderOutput)
}

type GatewayProviderMapOutput struct{ *pulumi.OutputState }

func (GatewayProviderMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GatewayProvider)(nil)).Elem()
}

func (o GatewayProviderMapOutput) ToGatewayProviderMapOutput() GatewayProviderMapOutput {
	return o
}

func (o GatewayProviderMapOutput) ToGatewayProviderMapOutputWithContext(ctx context.Context) GatewayProviderMapOutput {
	return o
}

func (o GatewayProviderMapOutput) MapIndex(k pulumi.StringInput) GatewayProviderOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GatewayProvider {
		return vs[0].(map[string]*GatewayProvider)[vs[1].(string)]
	}).(GatewayProviderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GatewayProviderInput)(nil)).Elem(), &GatewayProvider{})
	pulumi.RegisterInputType(reflect.TypeOf((*GatewayProviderArrayInput)(nil)).Elem(), GatewayProviderArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GatewayProviderMapInput)(nil)).Elem(), GatewayProviderMap{})
	pulumi.RegisterOutputType(GatewayProviderOutput{})
	pulumi.RegisterOutputType(GatewayProviderArrayOutput{})
	pulumi.RegisterOutputType(GatewayProviderMapOutput{})
}
