// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Resolves a PagerDuty service approved through a Logfire connection to the IDs required by a `pagerduty-integration` channel. PagerDuty's external service ID is resolved to Logfire's internal installation and resource IDs. The provider API key requires the `organization:read_channel` scope.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pydantic/pulumi-logfire/sdk/go/logfire"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			onCall, err := logfire.GetPagerdutyService(ctx, &logfire.GetPagerdutyServiceArgs{
//				AccountSubdomain:   "acme",
//				Region:             pulumi.StringRef("us"),
//				PagerdutyServiceId: "PABC123",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = logfire.NewChannel(ctx, "pagerdutyApp", &logfire.ChannelArgs{
//				Config: logfire.ChannelConfigArgs{
//					map[string]interface{}{
//						"type":      "pagerduty-integration",
//						"installId": onCall.InstallId,
//						"serviceId": onCall.ServiceId,
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetPagerdutyService(ctx *pulumi.Context, args *GetPagerdutyServiceArgs, opts ...pulumi.InvokeOption) (*GetPagerdutyServiceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPagerdutyServiceResult
	err := ctx.Invoke("logfire:index/getPagerdutyService:getPagerdutyService", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPagerdutyService.
type GetPagerdutyServiceArgs struct {
	// PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
	AccountSubdomain string `pulumi:"accountSubdomain"`
	// PagerDuty's service ID, such as `PABC123`.
	PagerdutyServiceId string `pulumi:"pagerdutyServiceId"`
	// PagerDuty account region (`us` or `eu`). Defaults to `us`.
	Region *string `pulumi:"region"`
}

// A collection of values returned by getPagerdutyService.
type GetPagerdutyServiceResult struct {
	// PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
	AccountSubdomain string `pulumi:"accountSubdomain"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Internal Logfire installation UUID for `logfire_channel.config.install_id`.
	InstallId string `pulumi:"installId"`
	// PagerDuty's service ID, such as `PABC123`.
	PagerdutyServiceId string `pulumi:"pagerdutyServiceId"`
	// PagerDuty account region (`us` or `eu`). Defaults to `us`.
	Region string `pulumi:"region"`
	// Internal Logfire resource UUID for `logfire_channel.config.service_id`.
	ServiceId string `pulumi:"serviceId"`
	// PagerDuty service name.
	ServiceName string `pulumi:"serviceName"`
}

func GetPagerdutyServiceOutput(ctx *pulumi.Context, args GetPagerdutyServiceOutputArgs, opts ...pulumi.InvokeOption) GetPagerdutyServiceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPagerdutyServiceResultOutput, error) {
			args := v.(GetPagerdutyServiceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("logfire:index/getPagerdutyService:getPagerdutyService", args, GetPagerdutyServiceResultOutput{}, options).(GetPagerdutyServiceResultOutput), nil
		}).(GetPagerdutyServiceResultOutput)
}

// A collection of arguments for invoking getPagerdutyService.
type GetPagerdutyServiceOutputArgs struct {
	// PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
	AccountSubdomain pulumi.StringInput `pulumi:"accountSubdomain"`
	// PagerDuty's service ID, such as `PABC123`.
	PagerdutyServiceId pulumi.StringInput `pulumi:"pagerdutyServiceId"`
	// PagerDuty account region (`us` or `eu`). Defaults to `us`.
	Region pulumi.StringPtrInput `pulumi:"region"`
}

func (GetPagerdutyServiceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPagerdutyServiceArgs)(nil)).Elem()
}

// A collection of values returned by getPagerdutyService.
type GetPagerdutyServiceResultOutput struct{ *pulumi.OutputState }

func (GetPagerdutyServiceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPagerdutyServiceResult)(nil)).Elem()
}

func (o GetPagerdutyServiceResultOutput) ToGetPagerdutyServiceResultOutput() GetPagerdutyServiceResultOutput {
	return o
}

func (o GetPagerdutyServiceResultOutput) ToGetPagerdutyServiceResultOutputWithContext(ctx context.Context) GetPagerdutyServiceResultOutput {
	return o
}

// PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
func (o GetPagerdutyServiceResultOutput) AccountSubdomain() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.AccountSubdomain }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPagerdutyServiceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.Id }).(pulumi.StringOutput)
}

// Internal Logfire installation UUID for `logfire_channel.config.install_id`.
func (o GetPagerdutyServiceResultOutput) InstallId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.InstallId }).(pulumi.StringOutput)
}

// PagerDuty's service ID, such as `PABC123`.
func (o GetPagerdutyServiceResultOutput) PagerdutyServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.PagerdutyServiceId }).(pulumi.StringOutput)
}

// PagerDuty account region (`us` or `eu`). Defaults to `us`.
func (o GetPagerdutyServiceResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.Region }).(pulumi.StringOutput)
}

// Internal Logfire resource UUID for `logfire_channel.config.service_id`.
func (o GetPagerdutyServiceResultOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.ServiceId }).(pulumi.StringOutput)
}

// PagerDuty service name.
func (o GetPagerdutyServiceResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPagerdutyServiceResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPagerdutyServiceResultOutput{})
}
