// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Manages a Logfire organization. This resource is only available for self-hosted deployments and requires an API key with a special organization scope.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pydantic/pulumi-logfire/sdk/go/logfire"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := logfire.NewOrganization(ctx, "example", &logfire.OrganizationArgs{
//				DeletionProtection: pulumi.Bool(false),
//				DisplayName:        pulumi.String("Terraform Example Org"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Organization struct {
	pulumi.CustomResourceState

	// Whether AI features are enabled.
	AiEnabled pulumi.BoolOutput `pulumi:"aiEnabled"`
	// Avatar URL.
	Avatar pulumi.StringOutput `pulumi:"avatar"`
	// Billing contact email.
	BillingEmail pulumi.StringOutput `pulumi:"billingEmail"`
	// Timestamp when the organization was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
	DeletionProtection pulumi.BoolOutput `pulumi:"deletionProtection"`
	// Organization description.
	Description pulumi.StringOutput `pulumi:"description"`
	// Display name shown in the UI.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Whether gateway features are enabled.
	GatewayEnabled pulumi.BoolOutput `pulumi:"gatewayEnabled"`
	// Organization GitHub handle.
	GithubHandle pulumi.StringOutput `pulumi:"githubHandle"`
	// Whether the organization has access to the admin panel.
	HasAdminPanel pulumi.BoolOutput `pulumi:"hasAdminPanel"`
	// Organization location.
	Location pulumi.StringOutput `pulumi:"location"`
	// Organization name/slug.
	Name pulumi.StringOutput `pulumi:"name"`
	// Timestamp when the organization was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewOrganization registers a new resource with the given unique name, arguments, and options.
func NewOrganization(ctx *pulumi.Context,
	name string, args *OrganizationArgs, opts ...pulumi.ResourceOption) (*Organization, error) {
	if args == nil {
		args = &OrganizationArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Organization
	err := ctx.RegisterResource("logfire:index/organization:Organization", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganization gets an existing Organization resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganization(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationState, opts ...pulumi.ResourceOption) (*Organization, error) {
	var resource Organization
	err := ctx.ReadResource("logfire:index/organization:Organization", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Organization resources.
type organizationState struct {
	// Whether AI features are enabled.
	AiEnabled *bool `pulumi:"aiEnabled"`
	// Avatar URL.
	Avatar *string `pulumi:"avatar"`
	// Billing contact email.
	BillingEmail *string `pulumi:"billingEmail"`
	// Timestamp when the organization was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// Organization description.
	Description *string `pulumi:"description"`
	// Display name shown in the UI.
	DisplayName *string `pulumi:"displayName"`
	// Whether gateway features are enabled.
	GatewayEnabled *bool `pulumi:"gatewayEnabled"`
	// Organization GitHub handle.
	GithubHandle *string `pulumi:"githubHandle"`
	// Whether the organization has access to the admin panel.
	HasAdminPanel *bool `pulumi:"hasAdminPanel"`
	// Organization location.
	Location *string `pulumi:"location"`
	// Organization name/slug.
	Name *string `pulumi:"name"`
	// Timestamp when the organization was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type OrganizationState struct {
	// Whether AI features are enabled.
	AiEnabled pulumi.BoolPtrInput
	// Avatar URL.
	Avatar pulumi.StringPtrInput
	// Billing contact email.
	BillingEmail pulumi.StringPtrInput
	// Timestamp when the organization was created.
	CreatedAt pulumi.StringPtrInput
	// Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
	DeletionProtection pulumi.BoolPtrInput
	// Organization description.
	Description pulumi.StringPtrInput
	// Display name shown in the UI.
	DisplayName pulumi.StringPtrInput
	// Whether gateway features are enabled.
	GatewayEnabled pulumi.BoolPtrInput
	// Organization GitHub handle.
	GithubHandle pulumi.StringPtrInput
	// Whether the organization has access to the admin panel.
	HasAdminPanel pulumi.BoolPtrInput
	// Organization location.
	Location pulumi.StringPtrInput
	// Organization name/slug.
	Name pulumi.StringPtrInput
	// Timestamp when the organization was last updated.
	UpdatedAt pulumi.StringPtrInput
}

func (OrganizationState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationState)(nil)).Elem()
}

type organizationArgs struct {
	// Avatar URL.
	Avatar *string `pulumi:"avatar"`
	// Billing contact email.
	BillingEmail *string `pulumi:"billingEmail"`
	// Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// Organization description.
	Description *string `pulumi:"description"`
	// Display name shown in the UI.
	DisplayName *string `pulumi:"displayName"`
	// Organization GitHub handle.
	GithubHandle *string `pulumi:"githubHandle"`
	// Organization location.
	Location *string `pulumi:"location"`
	// Organization name/slug.
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a Organization resource.
type OrganizationArgs struct {
	// Avatar URL.
	Avatar pulumi.StringPtrInput
	// Billing contact email.
	BillingEmail pulumi.StringPtrInput
	// Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
	DeletionProtection pulumi.BoolPtrInput
	// Organization description.
	Description pulumi.StringPtrInput
	// Display name shown in the UI.
	DisplayName pulumi.StringPtrInput
	// Organization GitHub handle.
	GithubHandle pulumi.StringPtrInput
	// Organization location.
	Location pulumi.StringPtrInput
	// Organization name/slug.
	Name pulumi.StringPtrInput
}

func (OrganizationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationArgs)(nil)).Elem()
}

type OrganizationInput interface {
	pulumi.Input

	ToOrganizationOutput() OrganizationOutput
	ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput
}

func (*Organization) ElementType() reflect.Type {
	return reflect.TypeOf((**Organization)(nil)).Elem()
}

func (i *Organization) ToOrganizationOutput() OrganizationOutput {
	return i.ToOrganizationOutputWithContext(context.Background())
}

func (i *Organization) ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationOutput)
}

// OrganizationArrayInput is an input type that accepts OrganizationArray and OrganizationArrayOutput values.
// You can construct a concrete instance of `OrganizationArrayInput` via:
//
//	OrganizationArray{ OrganizationArgs{...} }
type OrganizationArrayInput interface {
	pulumi.Input

	ToOrganizationArrayOutput() OrganizationArrayOutput
	ToOrganizationArrayOutputWithContext(context.Context) OrganizationArrayOutput
}

type OrganizationArray []OrganizationInput

func (OrganizationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Organization)(nil)).Elem()
}

func (i OrganizationArray) ToOrganizationArrayOutput() OrganizationArrayOutput {
	return i.ToOrganizationArrayOutputWithContext(context.Background())
}

func (i OrganizationArray) ToOrganizationArrayOutputWithContext(ctx context.Context) OrganizationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationArrayOutput)
}

// OrganizationMapInput is an input type that accepts OrganizationMap and OrganizationMapOutput values.
// You can construct a concrete instance of `OrganizationMapInput` via:
//
//	OrganizationMap{ "key": OrganizationArgs{...} }
type OrganizationMapInput interface {
	pulumi.Input

	ToOrganizationMapOutput() OrganizationMapOutput
	ToOrganizationMapOutputWithContext(context.Context) OrganizationMapOutput
}

type OrganizationMap map[string]OrganizationInput

func (OrganizationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Organization)(nil)).Elem()
}

func (i OrganizationMap) ToOrganizationMapOutput() OrganizationMapOutput {
	return i.ToOrganizationMapOutputWithContext(context.Background())
}

func (i OrganizationMap) ToOrganizationMapOutputWithContext(ctx context.Context) OrganizationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationMapOutput)
}

type OrganizationOutput struct{ *pulumi.OutputState }

func (OrganizationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Organization)(nil)).Elem()
}

func (o OrganizationOutput) ToOrganizationOutput() OrganizationOutput {
	return o
}

func (o OrganizationOutput) ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput {
	return o
}

// Whether AI features are enabled.
func (o OrganizationOutput) AiEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Organization) pulumi.BoolOutput { return v.AiEnabled }).(pulumi.BoolOutput)
}

// Avatar URL.
func (o OrganizationOutput) Avatar() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.Avatar }).(pulumi.StringOutput)
}

// Billing contact email.
func (o OrganizationOutput) BillingEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.BillingEmail }).(pulumi.StringOutput)
}

// Timestamp when the organization was created.
func (o OrganizationOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
func (o OrganizationOutput) DeletionProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v *Organization) pulumi.BoolOutput { return v.DeletionProtection }).(pulumi.BoolOutput)
}

// Organization description.
func (o OrganizationOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Display name shown in the UI.
func (o OrganizationOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// Whether gateway features are enabled.
func (o OrganizationOutput) GatewayEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Organization) pulumi.BoolOutput { return v.GatewayEnabled }).(pulumi.BoolOutput)
}

// Organization GitHub handle.
func (o OrganizationOutput) GithubHandle() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.GithubHandle }).(pulumi.StringOutput)
}

// Whether the organization has access to the admin panel.
func (o OrganizationOutput) HasAdminPanel() pulumi.BoolOutput {
	return o.ApplyT(func(v *Organization) pulumi.BoolOutput { return v.HasAdminPanel }).(pulumi.BoolOutput)
}

// Organization location.
func (o OrganizationOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// Organization name/slug.
func (o OrganizationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Timestamp when the organization was last updated.
func (o OrganizationOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type OrganizationArrayOutput struct{ *pulumi.OutputState }

func (OrganizationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Organization)(nil)).Elem()
}

func (o OrganizationArrayOutput) ToOrganizationArrayOutput() OrganizationArrayOutput {
	return o
}

func (o OrganizationArrayOutput) ToOrganizationArrayOutputWithContext(ctx context.Context) OrganizationArrayOutput {
	return o
}

func (o OrganizationArrayOutput) Index(i pulumi.IntInput) OrganizationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Organization {
		return vs[0].([]*Organization)[vs[1].(int)]
	}).(OrganizationOutput)
}

type OrganizationMapOutput struct{ *pulumi.OutputState }

func (OrganizationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Organization)(nil)).Elem()
}

func (o OrganizationMapOutput) ToOrganizationMapOutput() OrganizationMapOutput {
	return o
}

func (o OrganizationMapOutput) ToOrganizationMapOutputWithContext(ctx context.Context) OrganizationMapOutput {
	return o
}

func (o OrganizationMapOutput) MapIndex(k pulumi.StringInput) OrganizationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Organization {
		return vs[0].(map[string]*Organization)[vs[1].(string)]
	}).(OrganizationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationInput)(nil)).Elem(), &Organization{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationArrayInput)(nil)).Elem(), OrganizationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationMapInput)(nil)).Elem(), OrganizationMap{})
	pulumi.RegisterOutputType(OrganizationOutput{})
	pulumi.RegisterOutputType(OrganizationArrayOutput{})
	pulumi.RegisterOutputType(OrganizationMapOutput{})
}
