// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Manages a Logfire read token.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pydantic/pulumi-logfire/sdk/go/logfire"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			exampleProject, err := logfire.NewProject(ctx, "exampleProject", nil)
//			if err != nil {
//				return err
//			}
//			_, err = logfire.NewReadToken(ctx, "exampleReadToken", &logfire.ReadTokenArgs{
//				ProjectId: exampleProject.ID(),
//				ExpiresAt: pulumi.String("2099-12-31T23:59:59Z"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type ReadToken struct {
	pulumi.CustomResourceState

	// Timestamp when the token was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Display name of the user that created the token.
	CreatedByName pulumi.StringOutput `pulumi:"createdByName"`
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description pulumi.StringOutput `pulumi:"description"`
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt pulumi.StringPtrOutput `pulumi:"expiresAt"`
	// UUID of the project that owns the token.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Name of the project that owns the token.
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// The generated read token. Only returned on creation.
	Token pulumi.StringOutput `pulumi:"token"`
	// Prefix of the generated read token.
	TokenPrefix pulumi.StringOutput `pulumi:"tokenPrefix"`
}

// NewReadToken registers a new resource with the given unique name, arguments, and options.
func NewReadToken(ctx *pulumi.Context,
	name string, args *ReadTokenArgs, opts ...pulumi.ResourceOption) (*ReadToken, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ReadToken
	err := ctx.RegisterResource("logfire:index/readToken:ReadToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReadToken gets an existing ReadToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReadToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ReadTokenState, opts ...pulumi.ResourceOption) (*ReadToken, error) {
	var resource ReadToken
	err := ctx.ReadResource("logfire:index/readToken:ReadToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ReadToken resources.
type readTokenState struct {
	// Timestamp when the token was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Display name of the user that created the token.
	CreatedByName *string `pulumi:"createdByName"`
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description *string `pulumi:"description"`
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt *string `pulumi:"expiresAt"`
	// UUID of the project that owns the token.
	ProjectId *string `pulumi:"projectId"`
	// Name of the project that owns the token.
	ProjectName *string `pulumi:"projectName"`
	// The generated read token. Only returned on creation.
	Token *string `pulumi:"token"`
	// Prefix of the generated read token.
	TokenPrefix *string `pulumi:"tokenPrefix"`
}

type ReadTokenState struct {
	// Timestamp when the token was created.
	CreatedAt pulumi.StringPtrInput
	// Display name of the user that created the token.
	CreatedByName pulumi.StringPtrInput
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description pulumi.StringPtrInput
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt pulumi.StringPtrInput
	// UUID of the project that owns the token.
	ProjectId pulumi.StringPtrInput
	// Name of the project that owns the token.
	ProjectName pulumi.StringPtrInput
	// The generated read token. Only returned on creation.
	Token pulumi.StringPtrInput
	// Prefix of the generated read token.
	TokenPrefix pulumi.StringPtrInput
}

func (ReadTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*readTokenState)(nil)).Elem()
}

type readTokenArgs struct {
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt *string `pulumi:"expiresAt"`
	// UUID of the project that owns the token.
	ProjectId string `pulumi:"projectId"`
}

// The set of arguments for constructing a ReadToken resource.
type ReadTokenArgs struct {
	// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
	ExpiresAt pulumi.StringPtrInput
	// UUID of the project that owns the token.
	ProjectId pulumi.StringInput
}

func (ReadTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*readTokenArgs)(nil)).Elem()
}

type ReadTokenInput interface {
	pulumi.Input

	ToReadTokenOutput() ReadTokenOutput
	ToReadTokenOutputWithContext(ctx context.Context) ReadTokenOutput
}

func (*ReadToken) ElementType() reflect.Type {
	return reflect.TypeOf((**ReadToken)(nil)).Elem()
}

func (i *ReadToken) ToReadTokenOutput() ReadTokenOutput {
	return i.ToReadTokenOutputWithContext(context.Background())
}

func (i *ReadToken) ToReadTokenOutputWithContext(ctx context.Context) ReadTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReadTokenOutput)
}

// ReadTokenArrayInput is an input type that accepts ReadTokenArray and ReadTokenArrayOutput values.
// You can construct a concrete instance of `ReadTokenArrayInput` via:
//
//	ReadTokenArray{ ReadTokenArgs{...} }
type ReadTokenArrayInput interface {
	pulumi.Input

	ToReadTokenArrayOutput() ReadTokenArrayOutput
	ToReadTokenArrayOutputWithContext(context.Context) ReadTokenArrayOutput
}

type ReadTokenArray []ReadTokenInput

func (ReadTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReadToken)(nil)).Elem()
}

func (i ReadTokenArray) ToReadTokenArrayOutput() ReadTokenArrayOutput {
	return i.ToReadTokenArrayOutputWithContext(context.Background())
}

func (i ReadTokenArray) ToReadTokenArrayOutputWithContext(ctx context.Context) ReadTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReadTokenArrayOutput)
}

// ReadTokenMapInput is an input type that accepts ReadTokenMap and ReadTokenMapOutput values.
// You can construct a concrete instance of `ReadTokenMapInput` via:
//
//	ReadTokenMap{ "key": ReadTokenArgs{...} }
type ReadTokenMapInput interface {
	pulumi.Input

	ToReadTokenMapOutput() ReadTokenMapOutput
	ToReadTokenMapOutputWithContext(context.Context) ReadTokenMapOutput
}

type ReadTokenMap map[string]ReadTokenInput

func (ReadTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReadToken)(nil)).Elem()
}

func (i ReadTokenMap) ToReadTokenMapOutput() ReadTokenMapOutput {
	return i.ToReadTokenMapOutputWithContext(context.Background())
}

func (i ReadTokenMap) ToReadTokenMapOutputWithContext(ctx context.Context) ReadTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReadTokenMapOutput)
}

type ReadTokenOutput struct{ *pulumi.OutputState }

func (ReadTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ReadToken)(nil)).Elem()
}

func (o ReadTokenOutput) ToReadTokenOutput() ReadTokenOutput {
	return o
}

func (o ReadTokenOutput) ToReadTokenOutputWithContext(ctx context.Context) ReadTokenOutput {
	return o
}

// Timestamp when the token was created.
func (o ReadTokenOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Display name of the user that created the token.
func (o ReadTokenOutput) CreatedByName() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.CreatedByName }).(pulumi.StringOutput)
}

// Description is fixed to "Created by Public API" for provider-managed tokens.
func (o ReadTokenOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
func (o ReadTokenOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringPtrOutput { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// UUID of the project that owns the token.
func (o ReadTokenOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Name of the project that owns the token.
func (o ReadTokenOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// The generated read token. Only returned on creation.
func (o ReadTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// Prefix of the generated read token.
func (o ReadTokenOutput) TokenPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *ReadToken) pulumi.StringOutput { return v.TokenPrefix }).(pulumi.StringOutput)
}

type ReadTokenArrayOutput struct{ *pulumi.OutputState }

func (ReadTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReadToken)(nil)).Elem()
}

func (o ReadTokenArrayOutput) ToReadTokenArrayOutput() ReadTokenArrayOutput {
	return o
}

func (o ReadTokenArrayOutput) ToReadTokenArrayOutputWithContext(ctx context.Context) ReadTokenArrayOutput {
	return o
}

func (o ReadTokenArrayOutput) Index(i pulumi.IntInput) ReadTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ReadToken {
		return vs[0].([]*ReadToken)[vs[1].(int)]
	}).(ReadTokenOutput)
}

type ReadTokenMapOutput struct{ *pulumi.OutputState }

func (ReadTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReadToken)(nil)).Elem()
}

func (o ReadTokenMapOutput) ToReadTokenMapOutput() ReadTokenMapOutput {
	return o
}

func (o ReadTokenMapOutput) ToReadTokenMapOutputWithContext(ctx context.Context) ReadTokenMapOutput {
	return o
}

func (o ReadTokenMapOutput) MapIndex(k pulumi.StringInput) ReadTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ReadToken {
		return vs[0].(map[string]*ReadToken)[vs[1].(string)]
	}).(ReadTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ReadTokenInput)(nil)).Elem(), &ReadToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReadTokenArrayInput)(nil)).Elem(), ReadTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReadTokenMapInput)(nil)).Elem(), ReadTokenMap{})
	pulumi.RegisterOutputType(ReadTokenOutput{})
	pulumi.RegisterOutputType(ReadTokenArrayOutput{})
	pulumi.RegisterOutputType(ReadTokenMapOutput{})
}
