// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Manages an organization-level Logfire delivery schedule. A channel assignment with a `scheduleId` notifies its channel only inside the schedule's windows. Use it in `channelAssignments` on `Alert` and in `alerts.<tier>.channel_assignments` on `Slo`. Deleting a schedule makes the channel assignments that use it notify at all times. The provider credential needs `organization:read_channel` and `organization:write_channel`. The schedules API needs Logfire v2026-09-23.01 or newer.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pydantic/pulumi-logfire/sdk/go/logfire"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Weekday office hours in London. Use the schedule in a channel assignment on
//			// `logfire_alert` or `logfire_slo` to notify a channel only inside its windows.
//			_, err := logfire.NewSchedule(ctx, "officeHours", &logfire.ScheduleArgs{
//				Label:    pulumi.String("Office hours"),
//				Timezone: pulumi.String("Europe/London"),
//				Windows: logfire.ScheduleWindowArray{
//					&logfire.ScheduleWindowArgs{
//						Days: pulumi.IntArray{
//							pulumi.Int(1),
//							pulumi.Int(2),
//							pulumi.Int(3),
//							pulumi.Int(4),
//							pulumi.Int(5),
//						},
//						End_time:   "18:00",
//						Start_time: "09:00",
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Several windows: weekday evenings and all of the weekend.
//			_, err = logfire.NewSchedule(ctx, "outOfHours", &logfire.ScheduleArgs{
//				Label:    pulumi.String("Out of hours"),
//				Timezone: pulumi.String("America/New_York"),
//				Windows: logfire.ScheduleWindowArray{
//					&logfire.ScheduleWindowArgs{
//						Days: pulumi.IntArray{
//							pulumi.Int(1),
//							pulumi.Int(2),
//							pulumi.Int(3),
//							pulumi.Int(4),
//							pulumi.Int(5),
//						},
//						End_time:   "23:59",
//						Start_time: "18:00",
//					},
//					&logfire.ScheduleWindowArgs{
//						Days: pulumi.IntArray{
//							pulumi.Int(6),
//							pulumi.Int(7),
//						},
//						End_time:   "23:59",
//						Start_time: "00:00",
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Import an existing schedule by its UUID. The API has no schedule list and no
//
// lookup by label. The UUID is the `schedule_id` of any channel assignment that
//
// uses the schedule, for example in `logfire_slo.alerts` or in the alert
//
// API response.
//
// ```sh
// $ pulumi import logfire:index/schedule:Schedule office_hours' "9f9b2f9e-aaaa-bbbb-cccc-ddddeeeeffff"
// ```
type Schedule struct {
	pulumi.CustomResourceState

	// Schedule name.
	Label pulumi.StringOutput `pulumi:"label"`
	// IANA time zone of the windows, for example `Europe/London`.
	Timezone pulumi.StringOutput `pulumi:"timezone"`
	// Time windows in which the schedule delivers. At least one.
	Windows ScheduleWindowArrayOutput `pulumi:"windows"`
}

// NewSchedule registers a new resource with the given unique name, arguments, and options.
func NewSchedule(ctx *pulumi.Context,
	name string, args *ScheduleArgs, opts ...pulumi.ResourceOption) (*Schedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Label == nil {
		return nil, errors.New("invalid value for required argument 'Label'")
	}
	if args.Timezone == nil {
		return nil, errors.New("invalid value for required argument 'Timezone'")
	}
	if args.Windows == nil {
		return nil, errors.New("invalid value for required argument 'Windows'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Schedule
	err := ctx.RegisterResource("logfire:index/schedule:Schedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSchedule gets an existing Schedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScheduleState, opts ...pulumi.ResourceOption) (*Schedule, error) {
	var resource Schedule
	err := ctx.ReadResource("logfire:index/schedule:Schedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Schedule resources.
type scheduleState struct {
	// Schedule name.
	Label *string `pulumi:"label"`
	// IANA time zone of the windows, for example `Europe/London`.
	Timezone *string `pulumi:"timezone"`
	// Time windows in which the schedule delivers. At least one.
	Windows []ScheduleWindow `pulumi:"windows"`
}

type ScheduleState struct {
	// Schedule name.
	Label pulumi.StringPtrInput
	// IANA time zone of the windows, for example `Europe/London`.
	Timezone pulumi.StringPtrInput
	// Time windows in which the schedule delivers. At least one.
	Windows ScheduleWindowArrayInput
}

func (ScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleState)(nil)).Elem()
}

type scheduleArgs struct {
	// Schedule name.
	Label string `pulumi:"label"`
	// IANA time zone of the windows, for example `Europe/London`.
	Timezone string `pulumi:"timezone"`
	// Time windows in which the schedule delivers. At least one.
	Windows []ScheduleWindow `pulumi:"windows"`
}

// The set of arguments for constructing a Schedule resource.
type ScheduleArgs struct {
	// Schedule name.
	Label pulumi.StringInput
	// IANA time zone of the windows, for example `Europe/London`.
	Timezone pulumi.StringInput
	// Time windows in which the schedule delivers. At least one.
	Windows ScheduleWindowArrayInput
}

func (ScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleArgs)(nil)).Elem()
}

type ScheduleInput interface {
	pulumi.Input

	ToScheduleOutput() ScheduleOutput
	ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput
}

func (*Schedule) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (i *Schedule) ToScheduleOutput() ScheduleOutput {
	return i.ToScheduleOutputWithContext(context.Background())
}

func (i *Schedule) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleOutput)
}

// ScheduleArrayInput is an input type that accepts ScheduleArray and ScheduleArrayOutput values.
// You can construct a concrete instance of `ScheduleArrayInput` via:
//
//	ScheduleArray{ ScheduleArgs{...} }
type ScheduleArrayInput interface {
	pulumi.Input

	ToScheduleArrayOutput() ScheduleArrayOutput
	ToScheduleArrayOutputWithContext(context.Context) ScheduleArrayOutput
}

type ScheduleArray []ScheduleInput

func (ScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schedule)(nil)).Elem()
}

func (i ScheduleArray) ToScheduleArrayOutput() ScheduleArrayOutput {
	return i.ToScheduleArrayOutputWithContext(context.Background())
}

func (i ScheduleArray) ToScheduleArrayOutputWithContext(ctx context.Context) ScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleArrayOutput)
}

// ScheduleMapInput is an input type that accepts ScheduleMap and ScheduleMapOutput values.
// You can construct a concrete instance of `ScheduleMapInput` via:
//
//	ScheduleMap{ "key": ScheduleArgs{...} }
type ScheduleMapInput interface {
	pulumi.Input

	ToScheduleMapOutput() ScheduleMapOutput
	ToScheduleMapOutputWithContext(context.Context) ScheduleMapOutput
}

type ScheduleMap map[string]ScheduleInput

func (ScheduleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schedule)(nil)).Elem()
}

func (i ScheduleMap) ToScheduleMapOutput() ScheduleMapOutput {
	return i.ToScheduleMapOutputWithContext(context.Background())
}

func (i ScheduleMap) ToScheduleMapOutputWithContext(ctx context.Context) ScheduleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleMapOutput)
}

type ScheduleOutput struct{ *pulumi.OutputState }

func (ScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (o ScheduleOutput) ToScheduleOutput() ScheduleOutput {
	return o
}

func (o ScheduleOutput) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return o
}

// Schedule name.
func (o ScheduleOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Label }).(pulumi.StringOutput)
}

// IANA time zone of the windows, for example `Europe/London`.
func (o ScheduleOutput) Timezone() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Timezone }).(pulumi.StringOutput)
}

// Time windows in which the schedule delivers. At least one.
func (o ScheduleOutput) Windows() ScheduleWindowArrayOutput {
	return o.ApplyT(func(v *Schedule) ScheduleWindowArrayOutput { return v.Windows }).(ScheduleWindowArrayOutput)
}

type ScheduleArrayOutput struct{ *pulumi.OutputState }

func (ScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schedule)(nil)).Elem()
}

func (o ScheduleArrayOutput) ToScheduleArrayOutput() ScheduleArrayOutput {
	return o
}

func (o ScheduleArrayOutput) ToScheduleArrayOutputWithContext(ctx context.Context) ScheduleArrayOutput {
	return o
}

func (o ScheduleArrayOutput) Index(i pulumi.IntInput) ScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Schedule {
		return vs[0].([]*Schedule)[vs[1].(int)]
	}).(ScheduleOutput)
}

type ScheduleMapOutput struct{ *pulumi.OutputState }

func (ScheduleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schedule)(nil)).Elem()
}

func (o ScheduleMapOutput) ToScheduleMapOutput() ScheduleMapOutput {
	return o
}

func (o ScheduleMapOutput) ToScheduleMapOutputWithContext(ctx context.Context) ScheduleMapOutput {
	return o
}

func (o ScheduleMapOutput) MapIndex(k pulumi.StringInput) ScheduleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Schedule {
		return vs[0].(map[string]*Schedule)[vs[1].(string)]
	}).(ScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleInput)(nil)).Elem(), &Schedule{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleArrayInput)(nil)).Elem(), ScheduleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleMapInput)(nil)).Elem(), ScheduleMap{})
	pulumi.RegisterOutputType(ScheduleOutput{})
	pulumi.RegisterOutputType(ScheduleArrayOutput{})
	pulumi.RegisterOutputType(ScheduleMapOutput{})
}
