// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logfire

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

// Manages a Logfire write token.
type WriteToken struct {
	pulumi.CustomResourceState

	// Timestamp when the token was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Display name of the user that created the token.
	CreatedByName pulumi.StringOutput `pulumi:"createdByName"`
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description pulumi.StringOutput `pulumi:"description"`
	// UUID of the project that owns the token.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Name of the project that owns the token.
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// The generated write token. Only returned on creation.
	Token pulumi.StringOutput `pulumi:"token"`
	// Prefix of the generated write token.
	TokenPrefix pulumi.StringOutput `pulumi:"tokenPrefix"`
}

// NewWriteToken registers a new resource with the given unique name, arguments, and options.
func NewWriteToken(ctx *pulumi.Context,
	name string, args *WriteTokenArgs, opts ...pulumi.ResourceOption) (*WriteToken, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WriteToken
	err := ctx.RegisterResource("logfire:index/writeToken:WriteToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWriteToken gets an existing WriteToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWriteToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WriteTokenState, opts ...pulumi.ResourceOption) (*WriteToken, error) {
	var resource WriteToken
	err := ctx.ReadResource("logfire:index/writeToken:WriteToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WriteToken resources.
type writeTokenState struct {
	// Timestamp when the token was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Display name of the user that created the token.
	CreatedByName *string `pulumi:"createdByName"`
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description *string `pulumi:"description"`
	// UUID of the project that owns the token.
	ProjectId *string `pulumi:"projectId"`
	// Name of the project that owns the token.
	ProjectName *string `pulumi:"projectName"`
	// The generated write token. Only returned on creation.
	Token *string `pulumi:"token"`
	// Prefix of the generated write token.
	TokenPrefix *string `pulumi:"tokenPrefix"`
}

type WriteTokenState struct {
	// Timestamp when the token was created.
	CreatedAt pulumi.StringPtrInput
	// Display name of the user that created the token.
	CreatedByName pulumi.StringPtrInput
	// Description is fixed to "Created by Public API" for provider-managed tokens.
	Description pulumi.StringPtrInput
	// UUID of the project that owns the token.
	ProjectId pulumi.StringPtrInput
	// Name of the project that owns the token.
	ProjectName pulumi.StringPtrInput
	// The generated write token. Only returned on creation.
	Token pulumi.StringPtrInput
	// Prefix of the generated write token.
	TokenPrefix pulumi.StringPtrInput
}

func (WriteTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*writeTokenState)(nil)).Elem()
}

type writeTokenArgs struct {
	// UUID of the project that owns the token.
	ProjectId string `pulumi:"projectId"`
}

// The set of arguments for constructing a WriteToken resource.
type WriteTokenArgs struct {
	// UUID of the project that owns the token.
	ProjectId pulumi.StringInput
}

func (WriteTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*writeTokenArgs)(nil)).Elem()
}

type WriteTokenInput interface {
	pulumi.Input

	ToWriteTokenOutput() WriteTokenOutput
	ToWriteTokenOutputWithContext(ctx context.Context) WriteTokenOutput
}

func (*WriteToken) ElementType() reflect.Type {
	return reflect.TypeOf((**WriteToken)(nil)).Elem()
}

func (i *WriteToken) ToWriteTokenOutput() WriteTokenOutput {
	return i.ToWriteTokenOutputWithContext(context.Background())
}

func (i *WriteToken) ToWriteTokenOutputWithContext(ctx context.Context) WriteTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WriteTokenOutput)
}

// WriteTokenArrayInput is an input type that accepts WriteTokenArray and WriteTokenArrayOutput values.
// You can construct a concrete instance of `WriteTokenArrayInput` via:
//
//	WriteTokenArray{ WriteTokenArgs{...} }
type WriteTokenArrayInput interface {
	pulumi.Input

	ToWriteTokenArrayOutput() WriteTokenArrayOutput
	ToWriteTokenArrayOutputWithContext(context.Context) WriteTokenArrayOutput
}

type WriteTokenArray []WriteTokenInput

func (WriteTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WriteToken)(nil)).Elem()
}

func (i WriteTokenArray) ToWriteTokenArrayOutput() WriteTokenArrayOutput {
	return i.ToWriteTokenArrayOutputWithContext(context.Background())
}

func (i WriteTokenArray) ToWriteTokenArrayOutputWithContext(ctx context.Context) WriteTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WriteTokenArrayOutput)
}

// WriteTokenMapInput is an input type that accepts WriteTokenMap and WriteTokenMapOutput values.
// You can construct a concrete instance of `WriteTokenMapInput` via:
//
//	WriteTokenMap{ "key": WriteTokenArgs{...} }
type WriteTokenMapInput interface {
	pulumi.Input

	ToWriteTokenMapOutput() WriteTokenMapOutput
	ToWriteTokenMapOutputWithContext(context.Context) WriteTokenMapOutput
}

type WriteTokenMap map[string]WriteTokenInput

func (WriteTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WriteToken)(nil)).Elem()
}

func (i WriteTokenMap) ToWriteTokenMapOutput() WriteTokenMapOutput {
	return i.ToWriteTokenMapOutputWithContext(context.Background())
}

func (i WriteTokenMap) ToWriteTokenMapOutputWithContext(ctx context.Context) WriteTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WriteTokenMapOutput)
}

type WriteTokenOutput struct{ *pulumi.OutputState }

func (WriteTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WriteToken)(nil)).Elem()
}

func (o WriteTokenOutput) ToWriteTokenOutput() WriteTokenOutput {
	return o
}

func (o WriteTokenOutput) ToWriteTokenOutputWithContext(ctx context.Context) WriteTokenOutput {
	return o
}

// Timestamp when the token was created.
func (o WriteTokenOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Display name of the user that created the token.
func (o WriteTokenOutput) CreatedByName() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.CreatedByName }).(pulumi.StringOutput)
}

// Description is fixed to "Created by Public API" for provider-managed tokens.
func (o WriteTokenOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// UUID of the project that owns the token.
func (o WriteTokenOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Name of the project that owns the token.
func (o WriteTokenOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// The generated write token. Only returned on creation.
func (o WriteTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// Prefix of the generated write token.
func (o WriteTokenOutput) TokenPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *WriteToken) pulumi.StringOutput { return v.TokenPrefix }).(pulumi.StringOutput)
}

type WriteTokenArrayOutput struct{ *pulumi.OutputState }

func (WriteTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WriteToken)(nil)).Elem()
}

func (o WriteTokenArrayOutput) ToWriteTokenArrayOutput() WriteTokenArrayOutput {
	return o
}

func (o WriteTokenArrayOutput) ToWriteTokenArrayOutputWithContext(ctx context.Context) WriteTokenArrayOutput {
	return o
}

func (o WriteTokenArrayOutput) Index(i pulumi.IntInput) WriteTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WriteToken {
		return vs[0].([]*WriteToken)[vs[1].(int)]
	}).(WriteTokenOutput)
}

type WriteTokenMapOutput struct{ *pulumi.OutputState }

func (WriteTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WriteToken)(nil)).Elem()
}

func (o WriteTokenMapOutput) ToWriteTokenMapOutput() WriteTokenMapOutput {
	return o
}

func (o WriteTokenMapOutput) ToWriteTokenMapOutputWithContext(ctx context.Context) WriteTokenMapOutput {
	return o
}

func (o WriteTokenMapOutput) MapIndex(k pulumi.StringInput) WriteTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WriteToken {
		return vs[0].(map[string]*WriteToken)[vs[1].(string)]
	}).(WriteTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WriteTokenInput)(nil)).Elem(), &WriteToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*WriteTokenArrayInput)(nil)).Elem(), WriteTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WriteTokenMapInput)(nil)).Elem(), WriteTokenMap{})
	pulumi.RegisterOutputType(WriteTokenOutput{})
	pulumi.RegisterOutputType(WriteTokenArrayOutput{})
	pulumi.RegisterOutputType(WriteTokenMapOutput{})
}
