// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/pydantic/pulumi-logfire/sdk/go/logfire/internal"
)

var _ = internal.GetEnvOrDefault

// Bearer token. If omitted, the LOGFIRE_API_KEY environment variable is used.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "logfire:apiKey")
}

// Base URL for Logfire API. If omitted, the LOGFIRE_BASE_URL environment variable is used.
func GetBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "logfire:baseUrl")
}
