// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logfire.Outputs
{

    [OutputType]
    public sealed class ChannelConfig
    {
        /// <summary>
        /// Opsgenie API key.
        /// </summary>
        public readonly string? AuthKey;
        /// <summary>
        /// Webhook payload format.
        /// </summary>
        public readonly string? Format;
        /// <summary>
        /// Channel type (`Webhook` or `Opsgenie`).
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Webhook URL endpoint.
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private ChannelConfig(
            string? authKey,

            string? format,

            string type,

            string? url)
        {
            AuthKey = authKey;
            Format = format;
            Type = type;
            Url = url;
        }
    }
}
