// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ChannelConfig {
    /**
     * Opsgenie API key.
     */
    authKey?: string;
    /**
     * Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
     */
    channelId?: string;
    /**
     * Webhook payload format.
     */
    format?: string;
    /**
     * Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to `true` when omitted.
     */
    includeAgentPrompt?: boolean;
    /**
     * ID of the organization's Slack App installation, created by connecting Slack in the Logfire UI (Organization Settings > Integrations). The installation must belong to the same organization and be active.
     */
    installId?: string;
    /**
     * PagerDuty account region (`us` or `eu`). When omitted, Logfire uses the US Events API endpoint.
     */
    region?: string;
    /**
     * PagerDuty Events API v2 integration routing key.
     */
    routingKey?: string;
    /**
     * Channel type (`webhook`, `opsgenie`, `pagerduty`, or `slack-integration`).
     */
    type: string;
    /**
     * Webhook URL endpoint.
     */
    url?: string;
}

