# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .alert import *
from .channel import *
from .dashboard import *
from .project import *
from .provider import *
from .read_token import *
from .write_token import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_logfire.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_logfire.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "logfire",
  "mod": "index/alert",
  "fqn": "pulumi_logfire",
  "classes": {
   "logfire:index/alert:Alert": "Alert"
  }
 },
 {
  "pkg": "logfire",
  "mod": "index/channel",
  "fqn": "pulumi_logfire",
  "classes": {
   "logfire:index/channel:Channel": "Channel"
  }
 },
 {
  "pkg": "logfire",
  "mod": "index/dashboard",
  "fqn": "pulumi_logfire",
  "classes": {
   "logfire:index/dashboard:Dashboard": "Dashboard"
  }
 },
 {
  "pkg": "logfire",
  "mod": "index/project",
  "fqn": "pulumi_logfire",
  "classes": {
   "logfire:index/project:Project": "Project"
  }
 },
 {
  "pkg": "logfire",
  "mod": "index/readToken",
  "fqn": "pulumi_logfire",
  "classes": {
   "logfire:index/readToken:ReadToken": "ReadToken"
  }
 },
 {
  "pkg": "logfire",
  "mod": "index/writeToken",
  "fqn": "pulumi_logfire",
  "classes": {
   "logfire:index/writeToken:WriteToken": "WriteToken"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "logfire",
  "token": "pulumi:providers:logfire",
  "fqn": "pulumi_logfire",
  "class": "Provider"
 }
]
"""
)
