# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'AlertChannelAssignmentArgs',
    'AlertChannelAssignmentArgsDict',
    'ApiKeyGatewayArgs',
    'ApiKeyGatewayArgsDict',
    'ChannelConfigArgs',
    'ChannelConfigArgsDict',
    'ScheduleWindowArgs',
    'ScheduleWindowArgsDict',
    'SloAlertsArgs',
    'SloAlertsArgsDict',
    'SloAlertsFastArgs',
    'SloAlertsFastArgsDict',
    'SloAlertsFastChannelAssignmentArgs',
    'SloAlertsFastChannelAssignmentArgsDict',
    'SloAlertsMediumArgs',
    'SloAlertsMediumArgsDict',
    'SloAlertsMediumChannelAssignmentArgs',
    'SloAlertsMediumChannelAssignmentArgsDict',
    'SloAlertsSlowArgs',
    'SloAlertsSlowArgsDict',
    'SloAlertsSlowChannelAssignmentArgs',
    'SloAlertsSlowChannelAssignmentArgsDict',
]

MYPY = False

if not MYPY:
    class AlertChannelAssignmentArgsDict(TypedDict):
        channel_id: pulumi.Input[_builtins.str]
        """
        ID of the `Channel` to notify.
        """
        schedule_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
elif False:
    AlertChannelAssignmentArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class AlertChannelAssignmentArgs:
    def __init__(__self__, *,
                 channel_id: pulumi.Input[_builtins.str],
                 schedule_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] channel_id: ID of the `Channel` to notify.
        :param pulumi.Input[_builtins.str] schedule_id: ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        pulumi.set(__self__, "channel_id", channel_id)
        if schedule_id is not None:
            pulumi.set(__self__, "schedule_id", schedule_id)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the `Channel` to notify.
        """
        return pulumi.get(self, "channel_id")

    @channel_id.setter
    def channel_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "channel_id", value)

    @_builtins.property
    @pulumi.getter(name="scheduleId")
    def schedule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        return pulumi.get(self, "schedule_id")

    @schedule_id.setter
    def schedule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schedule_id", value)


if not MYPY:
    class ApiKeyGatewayArgsDict(TypedDict):
        cache_enabled: NotRequired[pulumi.Input[_builtins.bool]]
        """
        Whether gateway responses are cached. Null inherits the project default.
        """
        spending_limit_daily: NotRequired[pulumi.Input[_builtins.int]]
        """
        Maximum gateway spend in whole US dollars per day. Null means no limit.
        """
        spending_limit_monthly: NotRequired[pulumi.Input[_builtins.int]]
        """
        Maximum gateway spend in whole US dollars per month. Null means no limit.
        """
        spending_limit_total: NotRequired[pulumi.Input[_builtins.int]]
        """
        Maximum lifetime gateway spend in whole US dollars. Null means no limit.
        """
        spending_limit_weekly: NotRequired[pulumi.Input[_builtins.int]]
        """
        Maximum gateway spend in whole US dollars per week. Null means no limit.
        """
elif False:
    ApiKeyGatewayArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ApiKeyGatewayArgs:
    def __init__(__self__, *,
                 cache_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 spending_limit_daily: Optional[pulumi.Input[_builtins.int]] = None,
                 spending_limit_monthly: Optional[pulumi.Input[_builtins.int]] = None,
                 spending_limit_total: Optional[pulumi.Input[_builtins.int]] = None,
                 spending_limit_weekly: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.bool] cache_enabled: Whether gateway responses are cached. Null inherits the project default.
        :param pulumi.Input[_builtins.int] spending_limit_daily: Maximum gateway spend in whole US dollars per day. Null means no limit.
        :param pulumi.Input[_builtins.int] spending_limit_monthly: Maximum gateway spend in whole US dollars per month. Null means no limit.
        :param pulumi.Input[_builtins.int] spending_limit_total: Maximum lifetime gateway spend in whole US dollars. Null means no limit.
        :param pulumi.Input[_builtins.int] spending_limit_weekly: Maximum gateway spend in whole US dollars per week. Null means no limit.
        """
        if cache_enabled is not None:
            pulumi.set(__self__, "cache_enabled", cache_enabled)
        if spending_limit_daily is not None:
            pulumi.set(__self__, "spending_limit_daily", spending_limit_daily)
        if spending_limit_monthly is not None:
            pulumi.set(__self__, "spending_limit_monthly", spending_limit_monthly)
        if spending_limit_total is not None:
            pulumi.set(__self__, "spending_limit_total", spending_limit_total)
        if spending_limit_weekly is not None:
            pulumi.set(__self__, "spending_limit_weekly", spending_limit_weekly)

    @_builtins.property
    @pulumi.getter(name="cacheEnabled")
    def cache_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether gateway responses are cached. Null inherits the project default.
        """
        return pulumi.get(self, "cache_enabled")

    @cache_enabled.setter
    def cache_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "cache_enabled", value)

    @_builtins.property
    @pulumi.getter(name="spendingLimitDaily")
    def spending_limit_daily(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum gateway spend in whole US dollars per day. Null means no limit.
        """
        return pulumi.get(self, "spending_limit_daily")

    @spending_limit_daily.setter
    def spending_limit_daily(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "spending_limit_daily", value)

    @_builtins.property
    @pulumi.getter(name="spendingLimitMonthly")
    def spending_limit_monthly(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum gateway spend in whole US dollars per month. Null means no limit.
        """
        return pulumi.get(self, "spending_limit_monthly")

    @spending_limit_monthly.setter
    def spending_limit_monthly(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "spending_limit_monthly", value)

    @_builtins.property
    @pulumi.getter(name="spendingLimitTotal")
    def spending_limit_total(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum lifetime gateway spend in whole US dollars. Null means no limit.
        """
        return pulumi.get(self, "spending_limit_total")

    @spending_limit_total.setter
    def spending_limit_total(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "spending_limit_total", value)

    @_builtins.property
    @pulumi.getter(name="spendingLimitWeekly")
    def spending_limit_weekly(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum gateway spend in whole US dollars per week. Null means no limit.
        """
        return pulumi.get(self, "spending_limit_weekly")

    @spending_limit_weekly.setter
    def spending_limit_weekly(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "spending_limit_weekly", value)


if not MYPY:
    class ChannelConfigArgsDict(TypedDict):
        type: pulumi.Input[_builtins.str]
        """
        Channel type (`webhook`, `opsgenie`, `pagerduty`, `pagerduty-integration`, or `slack-integration`).
        """
        auth_key: NotRequired[pulumi.Input[_builtins.str]]
        """
        Opsgenie API key.
        """
        channel_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        """
        format: NotRequired[pulumi.Input[_builtins.str]]
        """
        Webhook payload format.
        """
        include_agent_prompt: NotRequired[pulumi.Input[_builtins.bool]]
        """
        Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to `true` when omitted.
        """
        install_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of the organization's Slack App or PagerDuty App installation, created by connecting the platform in the Logfire UI (Organization Settings > Connections). The installation must belong to the same organization, be active, and match the channel type.
        """
        region: NotRequired[pulumi.Input[_builtins.str]]
        """
        PagerDuty account region (`us` or `eu`). When omitted, Logfire uses the US Events API endpoint. Only for `pagerduty` channels; a `pagerduty-integration` channel takes its region from the connected account.
        """
        routing_key: NotRequired[pulumi.Input[_builtins.str]]
        """
        PagerDuty Events API v2 integration routing key. Only for `pagerduty` channels; `pagerduty-integration` channels resolve the key from the installation instead.
        """
        service_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        Logfire's ID (a UUID) for the PagerDuty service incidents are opened on, as approved for the installation when connecting PagerDuty. This is not PagerDuty's own service ID. Required for `pagerduty-integration` channels.
        """
        url: NotRequired[pulumi.Input[_builtins.str]]
        """
        Webhook URL endpoint.
        """
elif False:
    ChannelConfigArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ChannelConfigArgs:
    def __init__(__self__, *,
                 type: pulumi.Input[_builtins.str],
                 auth_key: Optional[pulumi.Input[_builtins.str]] = None,
                 channel_id: Optional[pulumi.Input[_builtins.str]] = None,
                 format: Optional[pulumi.Input[_builtins.str]] = None,
                 include_agent_prompt: Optional[pulumi.Input[_builtins.bool]] = None,
                 install_id: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 routing_key: Optional[pulumi.Input[_builtins.str]] = None,
                 service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] type: Channel type (`webhook`, `opsgenie`, `pagerduty`, `pagerduty-integration`, or `slack-integration`).
        :param pulumi.Input[_builtins.str] auth_key: Opsgenie API key.
        :param pulumi.Input[_builtins.str] channel_id: Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        :param pulumi.Input[_builtins.str] format: Webhook payload format.
        :param pulumi.Input[_builtins.bool] include_agent_prompt: Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to `true` when omitted.
        :param pulumi.Input[_builtins.str] install_id: ID of the organization's Slack App or PagerDuty App installation, created by connecting the platform in the Logfire UI (Organization Settings > Connections). The installation must belong to the same organization, be active, and match the channel type.
        :param pulumi.Input[_builtins.str] region: PagerDuty account region (`us` or `eu`). When omitted, Logfire uses the US Events API endpoint. Only for `pagerduty` channels; a `pagerduty-integration` channel takes its region from the connected account.
        :param pulumi.Input[_builtins.str] routing_key: PagerDuty Events API v2 integration routing key. Only for `pagerduty` channels; `pagerduty-integration` channels resolve the key from the installation instead.
        :param pulumi.Input[_builtins.str] service_id: Logfire's ID (a UUID) for the PagerDuty service incidents are opened on, as approved for the installation when connecting PagerDuty. This is not PagerDuty's own service ID. Required for `pagerduty-integration` channels.
        :param pulumi.Input[_builtins.str] url: Webhook URL endpoint.
        """
        pulumi.set(__self__, "type", type)
        if auth_key is not None:
            pulumi.set(__self__, "auth_key", auth_key)
        if channel_id is not None:
            pulumi.set(__self__, "channel_id", channel_id)
        if format is not None:
            pulumi.set(__self__, "format", format)
        if include_agent_prompt is not None:
            pulumi.set(__self__, "include_agent_prompt", include_agent_prompt)
        if install_id is not None:
            pulumi.set(__self__, "install_id", install_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if routing_key is not None:
            pulumi.set(__self__, "routing_key", routing_key)
        if service_id is not None:
            pulumi.set(__self__, "service_id", service_id)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Channel type (`webhook`, `opsgenie`, `pagerduty`, `pagerduty-integration`, or `slack-integration`).
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="authKey")
    def auth_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Opsgenie API key.
        """
        return pulumi.get(self, "auth_key")

    @auth_key.setter
    def auth_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_key", value)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        """
        return pulumi.get(self, "channel_id")

    @channel_id.setter
    def channel_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "channel_id", value)

    @_builtins.property
    @pulumi.getter
    def format(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Webhook payload format.
        """
        return pulumi.get(self, "format")

    @format.setter
    def format(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "format", value)

    @_builtins.property
    @pulumi.getter(name="includeAgentPrompt")
    def include_agent_prompt(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to `true` when omitted.
        """
        return pulumi.get(self, "include_agent_prompt")

    @include_agent_prompt.setter
    def include_agent_prompt(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "include_agent_prompt", value)

    @_builtins.property
    @pulumi.getter(name="installId")
    def install_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the organization's Slack App or PagerDuty App installation, created by connecting the platform in the Logfire UI (Organization Settings > Connections). The installation must belong to the same organization, be active, and match the channel type.
        """
        return pulumi.get(self, "install_id")

    @install_id.setter
    def install_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "install_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        PagerDuty account region (`us` or `eu`). When omitted, Logfire uses the US Events API endpoint. Only for `pagerduty` channels; a `pagerduty-integration` channel takes its region from the connected account.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="routingKey")
    def routing_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        PagerDuty Events API v2 integration routing key. Only for `pagerduty` channels; `pagerduty-integration` channels resolve the key from the installation instead.
        """
        return pulumi.get(self, "routing_key")

    @routing_key.setter
    def routing_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "routing_key", value)

    @_builtins.property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Logfire's ID (a UUID) for the PagerDuty service incidents are opened on, as approved for the installation when connecting PagerDuty. This is not PagerDuty's own service ID. Required for `pagerduty-integration` channels.
        """
        return pulumi.get(self, "service_id")

    @service_id.setter
    def service_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_id", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Webhook URL endpoint.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


if not MYPY:
    class ScheduleWindowArgsDict(TypedDict):
        days: pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]
        """
        ISO weekday numbers: `1` is Monday and `7` is Sunday.
        """
        end_time: pulumi.Input[_builtins.str]
        """
        End of the window, as 24-hour `HH:MM` or `HH:MM:SS` in `timezone`. A read keeps your spelling when it denotes the same time, and shows seconds only when they are not zero.
        """
        start_time: pulumi.Input[_builtins.str]
        """
        Start of the window, as 24-hour `HH:MM` or `HH:MM:SS` in `timezone`. A read keeps your spelling when it denotes the same time, and shows seconds only when they are not zero.
        """
elif False:
    ScheduleWindowArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ScheduleWindowArgs:
    def __init__(__self__, *,
                 days: pulumi.Input[Sequence[pulumi.Input[_builtins.int]]],
                 end_time: pulumi.Input[_builtins.str],
                 start_time: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] days: ISO weekday numbers: `1` is Monday and `7` is Sunday.
        :param pulumi.Input[_builtins.str] end_time: End of the window, as 24-hour `HH:MM` or `HH:MM:SS` in `timezone`. A read keeps your spelling when it denotes the same time, and shows seconds only when they are not zero.
        :param pulumi.Input[_builtins.str] start_time: Start of the window, as 24-hour `HH:MM` or `HH:MM:SS` in `timezone`. A read keeps your spelling when it denotes the same time, and shows seconds only when they are not zero.
        """
        pulumi.set(__self__, "days", days)
        pulumi.set(__self__, "end_time", end_time)
        pulumi.set(__self__, "start_time", start_time)

    @_builtins.property
    @pulumi.getter
    def days(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]:
        """
        ISO weekday numbers: `1` is Monday and `7` is Sunday.
        """
        return pulumi.get(self, "days")

    @days.setter
    def days(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]):
        pulumi.set(self, "days", value)

    @_builtins.property
    @pulumi.getter(name="endTime")
    def end_time(self) -> pulumi.Input[_builtins.str]:
        """
        End of the window, as 24-hour `HH:MM` or `HH:MM:SS` in `timezone`. A read keeps your spelling when it denotes the same time, and shows seconds only when they are not zero.
        """
        return pulumi.get(self, "end_time")

    @end_time.setter
    def end_time(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "end_time", value)

    @_builtins.property
    @pulumi.getter(name="startTime")
    def start_time(self) -> pulumi.Input[_builtins.str]:
        """
        Start of the window, as 24-hour `HH:MM` or `HH:MM:SS` in `timezone`. A read keeps your spelling when it denotes the same time, and shows seconds only when they are not zero.
        """
        return pulumi.get(self, "start_time")

    @start_time.setter
    def start_time(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "start_time", value)


if not MYPY:
    class SloAlertsArgsDict(TypedDict):
        fast: NotRequired[pulumi.Input['SloAlertsFastArgsDict']]
        """
        The `fast` burn-rate tier's alert (severity `page`). Omit it to leave that alert's channels as they are.
        """
        medium: NotRequired[pulumi.Input['SloAlertsMediumArgsDict']]
        """
        The `medium` burn-rate tier's alert (severity `page`). Omit it to leave that alert's channels as they are.
        """
        slow: NotRequired[pulumi.Input['SloAlertsSlowArgsDict']]
        """
        The `slow` burn-rate tier's alert (severity `ticket`). Omit it to leave that alert's channels as they are.
        """
elif False:
    SloAlertsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsArgs:
    def __init__(__self__, *,
                 fast: Optional[pulumi.Input['SloAlertsFastArgs']] = None,
                 medium: Optional[pulumi.Input['SloAlertsMediumArgs']] = None,
                 slow: Optional[pulumi.Input['SloAlertsSlowArgs']] = None):
        """
        :param pulumi.Input['SloAlertsFastArgs'] fast: The `fast` burn-rate tier's alert (severity `page`). Omit it to leave that alert's channels as they are.
        :param pulumi.Input['SloAlertsMediumArgs'] medium: The `medium` burn-rate tier's alert (severity `page`). Omit it to leave that alert's channels as they are.
        :param pulumi.Input['SloAlertsSlowArgs'] slow: The `slow` burn-rate tier's alert (severity `ticket`). Omit it to leave that alert's channels as they are.
        """
        if fast is not None:
            pulumi.set(__self__, "fast", fast)
        if medium is not None:
            pulumi.set(__self__, "medium", medium)
        if slow is not None:
            pulumi.set(__self__, "slow", slow)

    @_builtins.property
    @pulumi.getter
    def fast(self) -> Optional[pulumi.Input['SloAlertsFastArgs']]:
        """
        The `fast` burn-rate tier's alert (severity `page`). Omit it to leave that alert's channels as they are.
        """
        return pulumi.get(self, "fast")

    @fast.setter
    def fast(self, value: Optional[pulumi.Input['SloAlertsFastArgs']]):
        pulumi.set(self, "fast", value)

    @_builtins.property
    @pulumi.getter
    def medium(self) -> Optional[pulumi.Input['SloAlertsMediumArgs']]:
        """
        The `medium` burn-rate tier's alert (severity `page`). Omit it to leave that alert's channels as they are.
        """
        return pulumi.get(self, "medium")

    @medium.setter
    def medium(self, value: Optional[pulumi.Input['SloAlertsMediumArgs']]):
        pulumi.set(self, "medium", value)

    @_builtins.property
    @pulumi.getter
    def slow(self) -> Optional[pulumi.Input['SloAlertsSlowArgs']]:
        """
        The `slow` burn-rate tier's alert (severity `ticket`). Omit it to leave that alert's channels as they are.
        """
        return pulumi.get(self, "slow")

    @slow.setter
    def slow(self, value: Optional[pulumi.Input['SloAlertsSlowArgs']]):
        pulumi.set(self, "slow", value)


if not MYPY:
    class SloAlertsFastArgsDict(TypedDict):
        alert_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        """
        channel_assignments: NotRequired[pulumi.Input[Sequence[pulumi.Input['SloAlertsFastChannelAssignmentArgsDict']]]]
        """
        Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        """
        severity: NotRequired[pulumi.Input[_builtins.str]]
        """
        `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        """
        viable: NotRequired[pulumi.Input[_builtins.bool]]
        """
        False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
elif False:
    SloAlertsFastArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsFastArgs:
    def __init__(__self__, *,
                 alert_id: Optional[pulumi.Input[_builtins.str]] = None,
                 channel_assignments: Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsFastChannelAssignmentArgs']]]] = None,
                 severity: Optional[pulumi.Input[_builtins.str]] = None,
                 viable: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.str] alert_id: ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        :param pulumi.Input[Sequence[pulumi.Input['SloAlertsFastChannelAssignmentArgs']]] channel_assignments: Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        :param pulumi.Input[_builtins.str] severity: `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        :param pulumi.Input[_builtins.bool] viable: False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
        if alert_id is not None:
            pulumi.set(__self__, "alert_id", alert_id)
        if channel_assignments is not None:
            pulumi.set(__self__, "channel_assignments", channel_assignments)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if viable is not None:
            pulumi.set(__self__, "viable", viable)

    @_builtins.property
    @pulumi.getter(name="alertId")
    def alert_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        """
        return pulumi.get(self, "alert_id")

    @alert_id.setter
    def alert_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alert_id", value)

    @_builtins.property
    @pulumi.getter(name="channelAssignments")
    def channel_assignments(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsFastChannelAssignmentArgs']]]]:
        """
        Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        """
        return pulumi.get(self, "channel_assignments")

    @channel_assignments.setter
    def channel_assignments(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsFastChannelAssignmentArgs']]]]):
        pulumi.set(self, "channel_assignments", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def viable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
        return pulumi.get(self, "viable")

    @viable.setter
    def viable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "viable", value)


if not MYPY:
    class SloAlertsFastChannelAssignmentArgsDict(TypedDict):
        channel_id: pulumi.Input[_builtins.str]
        """
        ID of the `Channel` to notify.
        """
        schedule_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
elif False:
    SloAlertsFastChannelAssignmentArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsFastChannelAssignmentArgs:
    def __init__(__self__, *,
                 channel_id: pulumi.Input[_builtins.str],
                 schedule_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] channel_id: ID of the `Channel` to notify.
        :param pulumi.Input[_builtins.str] schedule_id: ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        pulumi.set(__self__, "channel_id", channel_id)
        if schedule_id is not None:
            pulumi.set(__self__, "schedule_id", schedule_id)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the `Channel` to notify.
        """
        return pulumi.get(self, "channel_id")

    @channel_id.setter
    def channel_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "channel_id", value)

    @_builtins.property
    @pulumi.getter(name="scheduleId")
    def schedule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        return pulumi.get(self, "schedule_id")

    @schedule_id.setter
    def schedule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schedule_id", value)


if not MYPY:
    class SloAlertsMediumArgsDict(TypedDict):
        alert_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        """
        channel_assignments: NotRequired[pulumi.Input[Sequence[pulumi.Input['SloAlertsMediumChannelAssignmentArgsDict']]]]
        """
        Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        """
        severity: NotRequired[pulumi.Input[_builtins.str]]
        """
        `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        """
        viable: NotRequired[pulumi.Input[_builtins.bool]]
        """
        False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
elif False:
    SloAlertsMediumArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsMediumArgs:
    def __init__(__self__, *,
                 alert_id: Optional[pulumi.Input[_builtins.str]] = None,
                 channel_assignments: Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsMediumChannelAssignmentArgs']]]] = None,
                 severity: Optional[pulumi.Input[_builtins.str]] = None,
                 viable: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.str] alert_id: ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        :param pulumi.Input[Sequence[pulumi.Input['SloAlertsMediumChannelAssignmentArgs']]] channel_assignments: Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        :param pulumi.Input[_builtins.str] severity: `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        :param pulumi.Input[_builtins.bool] viable: False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
        if alert_id is not None:
            pulumi.set(__self__, "alert_id", alert_id)
        if channel_assignments is not None:
            pulumi.set(__self__, "channel_assignments", channel_assignments)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if viable is not None:
            pulumi.set(__self__, "viable", viable)

    @_builtins.property
    @pulumi.getter(name="alertId")
    def alert_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        """
        return pulumi.get(self, "alert_id")

    @alert_id.setter
    def alert_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alert_id", value)

    @_builtins.property
    @pulumi.getter(name="channelAssignments")
    def channel_assignments(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsMediumChannelAssignmentArgs']]]]:
        """
        Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        """
        return pulumi.get(self, "channel_assignments")

    @channel_assignments.setter
    def channel_assignments(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsMediumChannelAssignmentArgs']]]]):
        pulumi.set(self, "channel_assignments", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def viable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
        return pulumi.get(self, "viable")

    @viable.setter
    def viable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "viable", value)


if not MYPY:
    class SloAlertsMediumChannelAssignmentArgsDict(TypedDict):
        channel_id: pulumi.Input[_builtins.str]
        """
        ID of the `Channel` to notify.
        """
        schedule_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
elif False:
    SloAlertsMediumChannelAssignmentArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsMediumChannelAssignmentArgs:
    def __init__(__self__, *,
                 channel_id: pulumi.Input[_builtins.str],
                 schedule_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] channel_id: ID of the `Channel` to notify.
        :param pulumi.Input[_builtins.str] schedule_id: ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        pulumi.set(__self__, "channel_id", channel_id)
        if schedule_id is not None:
            pulumi.set(__self__, "schedule_id", schedule_id)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the `Channel` to notify.
        """
        return pulumi.get(self, "channel_id")

    @channel_id.setter
    def channel_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "channel_id", value)

    @_builtins.property
    @pulumi.getter(name="scheduleId")
    def schedule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        return pulumi.get(self, "schedule_id")

    @schedule_id.setter
    def schedule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schedule_id", value)


if not MYPY:
    class SloAlertsSlowArgsDict(TypedDict):
        alert_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        """
        channel_assignments: NotRequired[pulumi.Input[Sequence[pulumi.Input['SloAlertsSlowChannelAssignmentArgsDict']]]]
        """
        Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        """
        severity: NotRequired[pulumi.Input[_builtins.str]]
        """
        `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        """
        viable: NotRequired[pulumi.Input[_builtins.bool]]
        """
        False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
elif False:
    SloAlertsSlowArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsSlowArgs:
    def __init__(__self__, *,
                 alert_id: Optional[pulumi.Input[_builtins.str]] = None,
                 channel_assignments: Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsSlowChannelAssignmentArgs']]]] = None,
                 severity: Optional[pulumi.Input[_builtins.str]] = None,
                 viable: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.str] alert_id: ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        :param pulumi.Input[Sequence[pulumi.Input['SloAlertsSlowChannelAssignmentArgs']]] channel_assignments: Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        :param pulumi.Input[_builtins.str] severity: `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        :param pulumi.Input[_builtins.bool] viable: False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
        if alert_id is not None:
            pulumi.set(__self__, "alert_id", alert_id)
        if channel_assignments is not None:
            pulumi.set(__self__, "channel_assignments", channel_assignments)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if viable is not None:
            pulumi.set(__self__, "viable", viable)

    @_builtins.property
    @pulumi.getter(name="alertId")
    def alert_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the tier's alert. Null only for an SLO created before Logfire kept all three tier alerts, when the tier could not fire at the SLO's target. The provider then plans an update of the SLO, even when no attribute changed, and that update creates the missing alert.
        """
        return pulumi.get(self, "alert_id")

    @alert_id.setter
    def alert_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alert_id", value)

    @_builtins.property
    @pulumi.getter(name="channelAssignments")
    def channel_assignments(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsSlowChannelAssignmentArgs']]]]:
        """
        Channels of this tier's alert, each with an optional delivery schedule. The provider writes the value to the alert on create, and on update when it differs from what the alert has. It is read back from the alert, so a change made on the Logfire alerts page shows as drift. Set it to `[]` to remove every channel. It is the same type as `logfire_alert.channel_assignments`.
        """
        return pulumi.get(self, "channel_assignments")

    @channel_assignments.setter
    def channel_assignments(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SloAlertsSlowChannelAssignmentArgs']]]]):
        pulumi.set(self, "channel_assignments", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        `page` for the `fast` and `medium` tiers, `ticket` for the `slow` tier.
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def viable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        False when the tier cannot fire at the SLO's `target_percent`. The alert keeps its channels but is not evaluated until a target change makes the tier viable.
        """
        return pulumi.get(self, "viable")

    @viable.setter
    def viable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "viable", value)


if not MYPY:
    class SloAlertsSlowChannelAssignmentArgsDict(TypedDict):
        channel_id: pulumi.Input[_builtins.str]
        """
        ID of the `Channel` to notify.
        """
        schedule_id: NotRequired[pulumi.Input[_builtins.str]]
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
elif False:
    SloAlertsSlowChannelAssignmentArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SloAlertsSlowChannelAssignmentArgs:
    def __init__(__self__, *,
                 channel_id: pulumi.Input[_builtins.str],
                 schedule_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] channel_id: ID of the `Channel` to notify.
        :param pulumi.Input[_builtins.str] schedule_id: ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        pulumi.set(__self__, "channel_id", channel_id)
        if schedule_id is not None:
            pulumi.set(__self__, "schedule_id", schedule_id)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the `Channel` to notify.
        """
        return pulumi.get(self, "channel_id")

    @channel_id.setter
    def channel_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "channel_id", value)

    @_builtins.property
    @pulumi.getter(name="scheduleId")
    def schedule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of a `Schedule`. The channel is notified only inside the schedule's windows. Omit it to notify the channel at all times.
        """
        return pulumi.get(self, "schedule_id")

    @schedule_id.setter
    def schedule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schedule_id", value)


