# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AlertArgs', 'Alert']

@pulumi.input_type
class AlertArgs:
    def __init__(__self__, *,
                 channel_ids: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 frequency: pulumi.Input[_builtins.str],
                 notify_when: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 query: pulumi.Input[_builtins.str],
                 time_window: pulumi.Input[_builtins.str],
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Alert resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channel_ids: Set of channel IDs to notify.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency as Go duration
        :param pulumi.Input[_builtins.str] notify_when: Notification rule. Must match API enum.
        :param pulumi.Input[_builtins.str] project_id: Project ID (UUID) used for alert API paths.
        :param pulumi.Input[_builtins.str] query: SQL / query string used by the alert.
        :param pulumi.Input[_builtins.str] time_window: Lookback window as Go duration
        :param pulumi.Input[_builtins.bool] active: Whether the alert is active (defaults to true on creation).
        :param pulumi.Input[_builtins.str] description: Alert description.
        :param pulumi.Input[_builtins.str] name: Alert name (unique per project).
        """
        pulumi.set(__self__, "channel_ids", channel_ids)
        pulumi.set(__self__, "frequency", frequency)
        pulumi.set(__self__, "notify_when", notify_when)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "query", query)
        pulumi.set(__self__, "time_window", time_window)
        if active is not None:
            pulumi.set(__self__, "active", active)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="channelIds")
    def channel_ids(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Set of channel IDs to notify.
        """
        return pulumi.get(self, "channel_ids")

    @channel_ids.setter
    def channel_ids(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "channel_ids", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Input[_builtins.str]:
        """
        Evaluation frequency as Go duration
        """
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter(name="notifyWhen")
    def notify_when(self) -> pulumi.Input[_builtins.str]:
        """
        Notification rule. Must match API enum.
        """
        return pulumi.get(self, "notify_when")

    @notify_when.setter
    def notify_when(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "notify_when", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        Project ID (UUID) used for alert API paths.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def query(self) -> pulumi.Input[_builtins.str]:
        """
        SQL / query string used by the alert.
        """
        return pulumi.get(self, "query")

    @query.setter
    def query(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "query", value)

    @_builtins.property
    @pulumi.getter(name="timeWindow")
    def time_window(self) -> pulumi.Input[_builtins.str]:
        """
        Lookback window as Go duration
        """
        return pulumi.get(self, "time_window")

    @time_window.setter
    def time_window(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "time_window", value)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the alert is active (defaults to true on creation).
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Alert description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Alert name (unique per project).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _AlertState:
    def __init__(__self__, *,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_when: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 query: Optional[pulumi.Input[_builtins.str]] = None,
                 time_window: Optional[pulumi.Input[_builtins.str]] = None,
                 watermark: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Alert resources.
        :param pulumi.Input[_builtins.bool] active: Whether the alert is active (defaults to true on creation).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channel_ids: Set of channel IDs to notify.
        :param pulumi.Input[_builtins.str] description: Alert description.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency as Go duration
        :param pulumi.Input[_builtins.str] name: Alert name (unique per project).
        :param pulumi.Input[_builtins.str] notify_when: Notification rule. Must match API enum.
        :param pulumi.Input[_builtins.str] project_id: Project ID (UUID) used for alert API paths.
        :param pulumi.Input[_builtins.str] query: SQL / query string used by the alert.
        :param pulumi.Input[_builtins.str] time_window: Lookback window as Go duration
        :param pulumi.Input[_builtins.str] watermark: Provider-managed watermark (lateness tolerance) sent to the API.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if channel_ids is not None:
            pulumi.set(__self__, "channel_ids", channel_ids)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if frequency is not None:
            pulumi.set(__self__, "frequency", frequency)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notify_when is not None:
            pulumi.set(__self__, "notify_when", notify_when)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if query is not None:
            pulumi.set(__self__, "query", query)
        if time_window is not None:
            pulumi.set(__self__, "time_window", time_window)
        if watermark is not None:
            pulumi.set(__self__, "watermark", watermark)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the alert is active (defaults to true on creation).
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter(name="channelIds")
    def channel_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Set of channel IDs to notify.
        """
        return pulumi.get(self, "channel_ids")

    @channel_ids.setter
    def channel_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "channel_ids", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Alert description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Evaluation frequency as Go duration
        """
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Alert name (unique per project).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="notifyWhen")
    def notify_when(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Notification rule. Must match API enum.
        """
        return pulumi.get(self, "notify_when")

    @notify_when.setter
    def notify_when(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "notify_when", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Project ID (UUID) used for alert API paths.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def query(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SQL / query string used by the alert.
        """
        return pulumi.get(self, "query")

    @query.setter
    def query(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "query", value)

    @_builtins.property
    @pulumi.getter(name="timeWindow")
    def time_window(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Lookback window as Go duration
        """
        return pulumi.get(self, "time_window")

    @time_window.setter
    def time_window(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "time_window", value)

    @_builtins.property
    @pulumi.getter
    def watermark(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Provider-managed watermark (lateness tolerance) sent to the API.
        """
        return pulumi.get(self, "watermark")

    @watermark.setter
    def watermark(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "watermark", value)


@pulumi.type_token("logfire:index/alert:Alert")
class Alert(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_when: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 query: Optional[pulumi.Input[_builtins.str]] = None,
                 time_window: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a Logfire alert.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Whether the alert is active (defaults to true on creation).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channel_ids: Set of channel IDs to notify.
        :param pulumi.Input[_builtins.str] description: Alert description.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency as Go duration
        :param pulumi.Input[_builtins.str] name: Alert name (unique per project).
        :param pulumi.Input[_builtins.str] notify_when: Notification rule. Must match API enum.
        :param pulumi.Input[_builtins.str] project_id: Project ID (UUID) used for alert API paths.
        :param pulumi.Input[_builtins.str] query: SQL / query string used by the alert.
        :param pulumi.Input[_builtins.str] time_window: Lookback window as Go duration
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AlertArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Logfire alert.

        :param str resource_name: The name of the resource.
        :param AlertArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AlertArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.bool]] = None,
                 channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_when: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 query: Optional[pulumi.Input[_builtins.str]] = None,
                 time_window: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AlertArgs.__new__(AlertArgs)

            __props__.__dict__["active"] = active
            if channel_ids is None and not opts.urn:
                raise TypeError("Missing required property 'channel_ids'")
            __props__.__dict__["channel_ids"] = channel_ids
            __props__.__dict__["description"] = description
            if frequency is None and not opts.urn:
                raise TypeError("Missing required property 'frequency'")
            __props__.__dict__["frequency"] = frequency
            __props__.__dict__["name"] = name
            if notify_when is None and not opts.urn:
                raise TypeError("Missing required property 'notify_when'")
            __props__.__dict__["notify_when"] = notify_when
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if query is None and not opts.urn:
                raise TypeError("Missing required property 'query'")
            __props__.__dict__["query"] = query
            if time_window is None and not opts.urn:
                raise TypeError("Missing required property 'time_window'")
            __props__.__dict__["time_window"] = time_window
            __props__.__dict__["watermark"] = None
        super(Alert, __self__).__init__(
            'logfire:index/alert:Alert',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            active: Optional[pulumi.Input[_builtins.bool]] = None,
            channel_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            frequency: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            notify_when: Optional[pulumi.Input[_builtins.str]] = None,
            project_id: Optional[pulumi.Input[_builtins.str]] = None,
            query: Optional[pulumi.Input[_builtins.str]] = None,
            time_window: Optional[pulumi.Input[_builtins.str]] = None,
            watermark: Optional[pulumi.Input[_builtins.str]] = None) -> 'Alert':
        """
        Get an existing Alert resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Whether the alert is active (defaults to true on creation).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channel_ids: Set of channel IDs to notify.
        :param pulumi.Input[_builtins.str] description: Alert description.
        :param pulumi.Input[_builtins.str] frequency: Evaluation frequency as Go duration
        :param pulumi.Input[_builtins.str] name: Alert name (unique per project).
        :param pulumi.Input[_builtins.str] notify_when: Notification rule. Must match API enum.
        :param pulumi.Input[_builtins.str] project_id: Project ID (UUID) used for alert API paths.
        :param pulumi.Input[_builtins.str] query: SQL / query string used by the alert.
        :param pulumi.Input[_builtins.str] time_window: Lookback window as Go duration
        :param pulumi.Input[_builtins.str] watermark: Provider-managed watermark (lateness tolerance) sent to the API.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AlertState.__new__(_AlertState)

        __props__.__dict__["active"] = active
        __props__.__dict__["channel_ids"] = channel_ids
        __props__.__dict__["description"] = description
        __props__.__dict__["frequency"] = frequency
        __props__.__dict__["name"] = name
        __props__.__dict__["notify_when"] = notify_when
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["query"] = query
        __props__.__dict__["time_window"] = time_window
        __props__.__dict__["watermark"] = watermark
        return Alert(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the alert is active (defaults to true on creation).
        """
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter(name="channelIds")
    def channel_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Set of channel IDs to notify.
        """
        return pulumi.get(self, "channel_ids")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Alert description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Output[_builtins.str]:
        """
        Evaluation frequency as Go duration
        """
        return pulumi.get(self, "frequency")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Alert name (unique per project).
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="notifyWhen")
    def notify_when(self) -> pulumi.Output[_builtins.str]:
        """
        Notification rule. Must match API enum.
        """
        return pulumi.get(self, "notify_when")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        Project ID (UUID) used for alert API paths.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def query(self) -> pulumi.Output[_builtins.str]:
        """
        SQL / query string used by the alert.
        """
        return pulumi.get(self, "query")

    @_builtins.property
    @pulumi.getter(name="timeWindow")
    def time_window(self) -> pulumi.Output[_builtins.str]:
        """
        Lookback window as Go duration
        """
        return pulumi.get(self, "time_window")

    @_builtins.property
    @pulumi.getter
    def watermark(self) -> pulumi.Output[_builtins.str]:
        """
        Provider-managed watermark (lateness tolerance) sent to the API.
        """
        return pulumi.get(self, "watermark")

