# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['FrontendApplicationTokenArgs', 'FrontendApplicationToken']

@pulumi.input_type
class FrontendApplicationTokenArgs:
    def __init__(__self__, *,
                 application_id: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 adopt_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 revoke_on_destroy: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a FrontendApplicationToken resource.
        :param pulumi.Input[_builtins.str] application_id: UUID of the frontend application.
        :param pulumi.Input[_builtins.str] project_id: UUID of the project that owns the application.
        :param pulumi.Input[_builtins.str] adopt_token_id: Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        :param pulumi.Input[_builtins.bool] revoke_on_destroy: Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        """
        pulumi.set(__self__, "application_id", application_id)
        pulumi.set(__self__, "project_id", project_id)
        if adopt_token_id is not None:
            pulumi.set(__self__, "adopt_token_id", adopt_token_id)
        if revoke_on_destroy is not None:
            pulumi.set(__self__, "revoke_on_destroy", revoke_on_destroy)

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> pulumi.Input[_builtins.str]:
        """
        UUID of the frontend application.
        """
        return pulumi.get(self, "application_id")

    @application_id.setter
    def application_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "application_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        UUID of the project that owns the application.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="adoptTokenId")
    def adopt_token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        """
        return pulumi.get(self, "adopt_token_id")

    @adopt_token_id.setter
    def adopt_token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "adopt_token_id", value)

    @_builtins.property
    @pulumi.getter(name="revokeOnDestroy")
    def revoke_on_destroy(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        """
        return pulumi.get(self, "revoke_on_destroy")

    @revoke_on_destroy.setter
    def revoke_on_destroy(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "revoke_on_destroy", value)


@pulumi.input_type
class _FrontendApplicationTokenState:
    def __init__(__self__, *,
                 adopt_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 application_id: Optional[pulumi.Input[_builtins.str]] = None,
                 created_at: Optional[pulumi.Input[_builtins.str]] = None,
                 last_used_at: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 revoke_on_destroy: Optional[pulumi.Input[_builtins.bool]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering FrontendApplicationToken resources.
        :param pulumi.Input[_builtins.str] adopt_token_id: Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        :param pulumi.Input[_builtins.str] application_id: UUID of the frontend application.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the token was created.
        :param pulumi.Input[_builtins.str] last_used_at: Timestamp when the token was last used, when known.
        :param pulumi.Input[_builtins.str] project_id: UUID of the project that owns the application.
        :param pulumi.Input[_builtins.bool] revoke_on_destroy: Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        :param pulumi.Input[_builtins.str] status: Token status. A managed token remains in state only while active.
        :param pulumi.Input[_builtins.str] token: Active restricted browser token. The provider recovers this value on refresh and import.
        """
        if adopt_token_id is not None:
            pulumi.set(__self__, "adopt_token_id", adopt_token_id)
        if application_id is not None:
            pulumi.set(__self__, "application_id", application_id)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if last_used_at is not None:
            pulumi.set(__self__, "last_used_at", last_used_at)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if revoke_on_destroy is not None:
            pulumi.set(__self__, "revoke_on_destroy", revoke_on_destroy)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="adoptTokenId")
    def adopt_token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        """
        return pulumi.get(self, "adopt_token_id")

    @adopt_token_id.setter
    def adopt_token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "adopt_token_id", value)

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        UUID of the frontend application.
        """
        return pulumi.get(self, "application_id")

    @application_id.setter
    def application_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application_id", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp when the token was created.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="lastUsedAt")
    def last_used_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp when the token was last used, when known.
        """
        return pulumi.get(self, "last_used_at")

    @last_used_at.setter
    def last_used_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "last_used_at", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        UUID of the project that owns the application.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="revokeOnDestroy")
    def revoke_on_destroy(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        """
        return pulumi.get(self, "revoke_on_destroy")

    @revoke_on_destroy.setter
    def revoke_on_destroy(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "revoke_on_destroy", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Token status. A managed token remains in state only while active.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Active restricted browser token. The provider recovers this value on refresh and import.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("logfire:index/frontendApplicationToken:FrontendApplicationToken")
class FrontendApplicationToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 adopt_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 application_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 revoke_on_destroy: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Experimental: the backing management API is currently enabled only in Logfire staging environments. Manages one active token for a Logfire frontend application. Rotate in two applies with two resource blocks: add the replacement and deploy its `token`, then remove the old resource to revoke it. The provider never revokes an old token while creating a new one. Token issuance is not retried automatically because the operation is not idempotent; after an uncertain failure, list the application's tokens and adopt the one unambiguous new active token. Before destroying the whole application tree, set the last token's `revoke_on_destroy` to `false` in a separate apply; application deletion then revokes every attached token.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_logfire as logfire

        current = logfire.FrontendApplicationToken("current",
            project_id=logfire_frontend_application["browser"]["project_id"],
            application_id=logfire_frontend_application["browser"]["id"],
            adopt_token_id=logfire_frontend_application["browser"]["token_id"])
        # First apply with both resources. Deploy the replacement output everywhere.
        # Then remove `current` and apply again to revoke the previous token.
        replacement = logfire.FrontendApplicationToken("replacement",
            project_id=logfire_frontend_application["browser"]["project_id"],
            application_id=logfire_frontend_application["browser"]["id"],
            revoke_on_destroy=True)
        pulumi.export("rotatedBrowserWriteToken", replacement.token)
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        ```sh
        $ pulumi import logfire:index/frontendApplicationToken:FrontendApplicationToken current "project-id/application-id/token-id"
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] adopt_token_id: Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        :param pulumi.Input[_builtins.str] application_id: UUID of the frontend application.
        :param pulumi.Input[_builtins.str] project_id: UUID of the project that owns the application.
        :param pulumi.Input[_builtins.bool] revoke_on_destroy: Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FrontendApplicationTokenArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Experimental: the backing management API is currently enabled only in Logfire staging environments. Manages one active token for a Logfire frontend application. Rotate in two applies with two resource blocks: add the replacement and deploy its `token`, then remove the old resource to revoke it. The provider never revokes an old token while creating a new one. Token issuance is not retried automatically because the operation is not idempotent; after an uncertain failure, list the application's tokens and adopt the one unambiguous new active token. Before destroying the whole application tree, set the last token's `revoke_on_destroy` to `false` in a separate apply; application deletion then revokes every attached token.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_logfire as logfire

        current = logfire.FrontendApplicationToken("current",
            project_id=logfire_frontend_application["browser"]["project_id"],
            application_id=logfire_frontend_application["browser"]["id"],
            adopt_token_id=logfire_frontend_application["browser"]["token_id"])
        # First apply with both resources. Deploy the replacement output everywhere.
        # Then remove `current` and apply again to revoke the previous token.
        replacement = logfire.FrontendApplicationToken("replacement",
            project_id=logfire_frontend_application["browser"]["project_id"],
            application_id=logfire_frontend_application["browser"]["id"],
            revoke_on_destroy=True)
        pulumi.export("rotatedBrowserWriteToken", replacement.token)
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        ```sh
        $ pulumi import logfire:index/frontendApplicationToken:FrontendApplicationToken current "project-id/application-id/token-id"
        ```

        :param str resource_name: The name of the resource.
        :param FrontendApplicationTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FrontendApplicationTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 adopt_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 application_id: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 revoke_on_destroy: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FrontendApplicationTokenArgs.__new__(FrontendApplicationTokenArgs)

            __props__.__dict__["adopt_token_id"] = adopt_token_id
            if application_id is None and not opts.urn:
                raise TypeError("Missing required property 'application_id'")
            __props__.__dict__["application_id"] = application_id
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["revoke_on_destroy"] = revoke_on_destroy
            __props__.__dict__["created_at"] = None
            __props__.__dict__["last_used_at"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["token"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(FrontendApplicationToken, __self__).__init__(
            'logfire:index/frontendApplicationToken:FrontendApplicationToken',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            adopt_token_id: Optional[pulumi.Input[_builtins.str]] = None,
            application_id: Optional[pulumi.Input[_builtins.str]] = None,
            created_at: Optional[pulumi.Input[_builtins.str]] = None,
            last_used_at: Optional[pulumi.Input[_builtins.str]] = None,
            project_id: Optional[pulumi.Input[_builtins.str]] = None,
            revoke_on_destroy: Optional[pulumi.Input[_builtins.bool]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            token: Optional[pulumi.Input[_builtins.str]] = None) -> 'FrontendApplicationToken':
        """
        Get an existing FrontendApplicationToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] adopt_token_id: Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        :param pulumi.Input[_builtins.str] application_id: UUID of the frontend application.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the token was created.
        :param pulumi.Input[_builtins.str] last_used_at: Timestamp when the token was last used, when known.
        :param pulumi.Input[_builtins.str] project_id: UUID of the project that owns the application.
        :param pulumi.Input[_builtins.bool] revoke_on_destroy: Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        :param pulumi.Input[_builtins.str] status: Token status. A managed token remains in state only while active.
        :param pulumi.Input[_builtins.str] token: Active restricted browser token. The provider recovers this value on refresh and import.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _FrontendApplicationTokenState.__new__(_FrontendApplicationTokenState)

        __props__.__dict__["adopt_token_id"] = adopt_token_id
        __props__.__dict__["application_id"] = application_id
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["last_used_at"] = last_used_at
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["revoke_on_destroy"] = revoke_on_destroy
        __props__.__dict__["status"] = status
        __props__.__dict__["token"] = token
        return FrontendApplicationToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="adoptTokenId")
    def adopt_token_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Existing active token to adopt instead of issuing another. Use the application's `token_id` for the initial handoff, then remove this resource only after a separately managed replacement has been deployed.
        """
        return pulumi.get(self, "adopt_token_id")

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> pulumi.Output[_builtins.str]:
        """
        UUID of the frontend application.
        """
        return pulumi.get(self, "application_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the token was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="lastUsedAt")
    def last_used_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the token was last used, when known.
        """
        return pulumi.get(self, "last_used_at")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        UUID of the project that owns the application.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter(name="revokeOnDestroy")
    def revoke_on_destroy(self) -> pulumi.Output[_builtins.bool]:
        """
        Revoke this token when its resource is destroyed. Before destroying the entire application tree, set this to `false` in a separate apply for the last token so application deletion can revoke all attached tokens.
        """
        return pulumi.get(self, "revoke_on_destroy")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Token status. A managed token remains in state only while active.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        Active restricted browser token. The provider recovers this value on refresh and import.
        """
        return pulumi.get(self, "token")

