# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['GatewayProviderArgs', 'GatewayProvider']

@pulumi.input_type
class GatewayProviderArgs:
    def __init__(__self__, *,
                 api_key: pulumi.Input[_builtins.str],
                 slug: pulumi.Input[_builtins.str],
                 vendor: pulumi.Input[_builtins.str],
                 bedrock_api: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_region: Optional[pulumi.Input[_builtins.str]] = None,
                 require_pricing: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a GatewayProvider resource.
        :param pulumi.Input[_builtins.str] slug: Organization-unique provider slug. Changing it replaces the provider.
        :param pulumi.Input[_builtins.str] vendor: Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        :param pulumi.Input[_builtins.str] bedrock_api: Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.str] bedrock_region: AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.bool] require_pricing: Require known model pricing before forwarding requests. Defaults to true.
        """
        pulumi.set(__self__, "api_key", api_key)
        pulumi.set(__self__, "slug", slug)
        pulumi.set(__self__, "vendor", vendor)
        if bedrock_api is not None:
            pulumi.set(__self__, "bedrock_api", bedrock_api)
        if bedrock_region is not None:
            pulumi.set(__self__, "bedrock_region", bedrock_region)
        if require_pricing is not None:
            pulumi.set(__self__, "require_pricing", require_pricing)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[_builtins.str]:
        """
        Organization-unique provider slug. Changing it replaces the provider.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter
    def vendor(self) -> pulumi.Input[_builtins.str]:
        """
        Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        """
        return pulumi.get(self, "vendor")

    @vendor.setter
    def vendor(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "vendor", value)

    @_builtins.property
    @pulumi.getter(name="bedrockApi")
    def bedrock_api(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        """
        return pulumi.get(self, "bedrock_api")

    @bedrock_api.setter
    def bedrock_api(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bedrock_api", value)

    @_builtins.property
    @pulumi.getter(name="bedrockRegion")
    def bedrock_region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        """
        return pulumi.get(self, "bedrock_region")

    @bedrock_region.setter
    def bedrock_region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bedrock_region", value)

    @_builtins.property
    @pulumi.getter(name="requirePricing")
    def require_pricing(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require known model pricing before forwarding requests. Defaults to true.
        """
        return pulumi.get(self, "require_pricing")

    @require_pricing.setter
    def require_pricing(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "require_pricing", value)


@pulumi.input_type
class _GatewayProviderState:
    def __init__(__self__, *,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_api: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_region: Optional[pulumi.Input[_builtins.str]] = None,
                 created_at: Optional[pulumi.Input[_builtins.str]] = None,
                 require_pricing: Optional[pulumi.Input[_builtins.bool]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 vendor: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering GatewayProvider resources.
        :param pulumi.Input[_builtins.str] bedrock_api: Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.str] bedrock_region: AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the provider was created.
        :param pulumi.Input[_builtins.bool] require_pricing: Require known model pricing before forwarding requests. Defaults to true.
        :param pulumi.Input[_builtins.str] slug: Organization-unique provider slug. Changing it replaces the provider.
        :param pulumi.Input[_builtins.str] vendor: Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        """
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if bedrock_api is not None:
            pulumi.set(__self__, "bedrock_api", bedrock_api)
        if bedrock_region is not None:
            pulumi.set(__self__, "bedrock_region", bedrock_region)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if require_pricing is not None:
            pulumi.set(__self__, "require_pricing", require_pricing)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if vendor is not None:
            pulumi.set(__self__, "vendor", vendor)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="bedrockApi")
    def bedrock_api(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        """
        return pulumi.get(self, "bedrock_api")

    @bedrock_api.setter
    def bedrock_api(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bedrock_api", value)

    @_builtins.property
    @pulumi.getter(name="bedrockRegion")
    def bedrock_region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        """
        return pulumi.get(self, "bedrock_region")

    @bedrock_region.setter
    def bedrock_region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "bedrock_region", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp when the provider was created.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="requirePricing")
    def require_pricing(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require known model pricing before forwarding requests. Defaults to true.
        """
        return pulumi.get(self, "require_pricing")

    @require_pricing.setter
    def require_pricing(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "require_pricing", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization-unique provider slug. Changing it replaces the provider.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter
    def vendor(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        """
        return pulumi.get(self, "vendor")

    @vendor.setter
    def vendor(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vendor", value)


@pulumi.type_token("logfire:index/gatewayProvider:GatewayProvider")
class GatewayProvider(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_api: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_region: Optional[pulumi.Input[_builtins.str]] = None,
                 require_pricing: Optional[pulumi.Input[_builtins.bool]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 vendor: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        ## Import

        Import a provider by UUID using the same organization's management token:

        terraform

        import {

          to = logfire_gateway_provider.openai

          id = "018f45c0-3cab-7b2f-a8f7-8a0b55a7ed11"

        }

        Or use the command line:

        Import an existing Gateway provider by its UUID, or by its organization-unique slug.

        The UUID comes from the provider list endpoint:

          curl -s -H "Authorization: Bearer $LOGFIRE_API_KEY" \\

            "$LOGFIRE_BASE_URL/api/v1/gateway/providers/" | jq '.providers[] | {id, slug}'

        By slug:

        ```sh
        $ pulumi import logfire:index/gatewayProvider:GatewayProvider openai' "openai"
        ```

        By UUID:

        ```sh
        $ pulumi import logfire:index/gatewayProvider:GatewayProvider openai' "018f45c0-3cab-7b2f-a8f7-8a0b55a7ed11"
        ```

        Import reads public configuration only. Set `api_key` in your configuration;

        the next apply writes that key to the imported provider. Import does not recover

        the existing secret.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] bedrock_api: Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.str] bedrock_region: AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.bool] require_pricing: Require known model pricing before forwarding requests. Defaults to true.
        :param pulumi.Input[_builtins.str] slug: Organization-unique provider slug. Changing it replaces the provider.
        :param pulumi.Input[_builtins.str] vendor: Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GatewayProviderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Import

        Import a provider by UUID using the same organization's management token:

        terraform

        import {

          to = logfire_gateway_provider.openai

          id = "018f45c0-3cab-7b2f-a8f7-8a0b55a7ed11"

        }

        Or use the command line:

        Import an existing Gateway provider by its UUID, or by its organization-unique slug.

        The UUID comes from the provider list endpoint:

          curl -s -H "Authorization: Bearer $LOGFIRE_API_KEY" \\

            "$LOGFIRE_BASE_URL/api/v1/gateway/providers/" | jq '.providers[] | {id, slug}'

        By slug:

        ```sh
        $ pulumi import logfire:index/gatewayProvider:GatewayProvider openai' "openai"
        ```

        By UUID:

        ```sh
        $ pulumi import logfire:index/gatewayProvider:GatewayProvider openai' "018f45c0-3cab-7b2f-a8f7-8a0b55a7ed11"
        ```

        Import reads public configuration only. Set `api_key` in your configuration;

        the next apply writes that key to the imported provider. Import does not recover

        the existing secret.

        :param str resource_name: The name of the resource.
        :param GatewayProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GatewayProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_api: Optional[pulumi.Input[_builtins.str]] = None,
                 bedrock_region: Optional[pulumi.Input[_builtins.str]] = None,
                 require_pricing: Optional[pulumi.Input[_builtins.bool]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 vendor: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GatewayProviderArgs.__new__(GatewayProviderArgs)

            if api_key is None and not opts.urn:
                raise TypeError("Missing required property 'api_key'")
            __props__.__dict__["api_key"] = None if api_key is None else pulumi.Output.secret(api_key)
            __props__.__dict__["bedrock_api"] = bedrock_api
            __props__.__dict__["bedrock_region"] = bedrock_region
            __props__.__dict__["require_pricing"] = require_pricing
            if slug is None and not opts.urn:
                raise TypeError("Missing required property 'slug'")
            __props__.__dict__["slug"] = slug
            if vendor is None and not opts.urn:
                raise TypeError("Missing required property 'vendor'")
            __props__.__dict__["vendor"] = vendor
            __props__.__dict__["created_at"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(GatewayProvider, __self__).__init__(
            'logfire:index/gatewayProvider:GatewayProvider',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            api_key: Optional[pulumi.Input[_builtins.str]] = None,
            bedrock_api: Optional[pulumi.Input[_builtins.str]] = None,
            bedrock_region: Optional[pulumi.Input[_builtins.str]] = None,
            created_at: Optional[pulumi.Input[_builtins.str]] = None,
            require_pricing: Optional[pulumi.Input[_builtins.bool]] = None,
            slug: Optional[pulumi.Input[_builtins.str]] = None,
            vendor: Optional[pulumi.Input[_builtins.str]] = None) -> 'GatewayProvider':
        """
        Get an existing GatewayProvider resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] bedrock_api: Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.str] bedrock_region: AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the provider was created.
        :param pulumi.Input[_builtins.bool] require_pricing: Require known model pricing before forwarding requests. Defaults to true.
        :param pulumi.Input[_builtins.str] slug: Organization-unique provider slug. Changing it replaces the provider.
        :param pulumi.Input[_builtins.str] vendor: Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GatewayProviderState.__new__(_GatewayProviderState)

        __props__.__dict__["api_key"] = api_key
        __props__.__dict__["bedrock_api"] = bedrock_api
        __props__.__dict__["bedrock_region"] = bedrock_region
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["require_pricing"] = require_pricing
        __props__.__dict__["slug"] = slug
        __props__.__dict__["vendor"] = vendor
        return GatewayProvider(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter(name="bedrockApi")
    def bedrock_api(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Bedrock API variant: runtime or mantle. Required only for bedrock; can be updated in place.
        """
        return pulumi.get(self, "bedrock_api")

    @_builtins.property
    @pulumi.getter(name="bedrockRegion")
    def bedrock_region(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        AWS region used to derive the Bedrock endpoint, for example us-east-1. Required only for bedrock; can be updated in place.
        """
        return pulumi.get(self, "bedrock_region")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the provider was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="requirePricing")
    def require_pricing(self) -> pulumi.Output[_builtins.bool]:
        """
        Require known model pricing before forwarding requests. Defaults to true.
        """
        return pulumi.get(self, "require_pricing")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        """
        Organization-unique provider slug. Changing it replaces the provider.
        """
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter
    def vendor(self) -> pulumi.Output[_builtins.str]:
        """
        Upstream vendor: openai, anthropic, bedrock, doubleword, groq, huggingface, or mistral. Changing it replaces the provider.
        """
        return pulumi.get(self, "vendor")

