# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'ChannelConfig',
]

@pulumi.output_type
class ChannelConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "authKey":
            suggest = "auth_key"
        elif key == "channelId":
            suggest = "channel_id"
        elif key == "includeAgentPrompt":
            suggest = "include_agent_prompt"
        elif key == "installId":
            suggest = "install_id"
        elif key == "routingKey":
            suggest = "routing_key"
        elif key == "serviceId":
            suggest = "service_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ChannelConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ChannelConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ChannelConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 type: _builtins.str,
                 auth_key: Optional[_builtins.str] = None,
                 channel_id: Optional[_builtins.str] = None,
                 format: Optional[_builtins.str] = None,
                 include_agent_prompt: Optional[_builtins.bool] = None,
                 install_id: Optional[_builtins.str] = None,
                 region: Optional[_builtins.str] = None,
                 routing_key: Optional[_builtins.str] = None,
                 service_id: Optional[_builtins.str] = None,
                 url: Optional[_builtins.str] = None):
        """
        :param _builtins.str type: Channel type (`webhook`, `opsgenie`, `pagerduty`, `pagerduty-integration`, or `slack-integration`).
        :param _builtins.str auth_key: Opsgenie API key.
        :param _builtins.str channel_id: Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        :param _builtins.str format: Webhook payload format.
        :param _builtins.bool include_agent_prompt: Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to `true` when omitted.
        :param _builtins.str install_id: ID of the organization's Slack App or PagerDuty App installation, created by connecting the platform in the Logfire UI (Organization Settings > Connections). The installation must belong to the same organization, be active, and match the channel type.
        :param _builtins.str region: PagerDuty account region (`us` or `eu`). When omitted, Logfire uses the US Events API endpoint. Only for `pagerduty` channels; a `pagerduty-integration` channel takes its region from the connected account.
        :param _builtins.str routing_key: PagerDuty Events API v2 integration routing key. Only for `pagerduty` channels; `pagerduty-integration` channels resolve the key from the installation instead.
        :param _builtins.str service_id: Logfire's ID (a UUID) for the PagerDuty service incidents are opened on, as approved for the installation when connecting PagerDuty. This is not PagerDuty's own service ID. Required for `pagerduty-integration` channels.
        :param _builtins.str url: Webhook URL endpoint.
        """
        pulumi.set(__self__, "type", type)
        if auth_key is not None:
            pulumi.set(__self__, "auth_key", auth_key)
        if channel_id is not None:
            pulumi.set(__self__, "channel_id", channel_id)
        if format is not None:
            pulumi.set(__self__, "format", format)
        if include_agent_prompt is not None:
            pulumi.set(__self__, "include_agent_prompt", include_agent_prompt)
        if install_id is not None:
            pulumi.set(__self__, "install_id", install_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if routing_key is not None:
            pulumi.set(__self__, "routing_key", routing_key)
        if service_id is not None:
            pulumi.set(__self__, "service_id", service_id)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Channel type (`webhook`, `opsgenie`, `pagerduty`, `pagerduty-integration`, or `slack-integration`).
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="authKey")
    def auth_key(self) -> Optional[_builtins.str]:
        """
        Opsgenie API key.
        """
        return pulumi.get(self, "auth_key")

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> Optional[_builtins.str]:
        """
        Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        """
        return pulumi.get(self, "channel_id")

    @_builtins.property
    @pulumi.getter
    def format(self) -> Optional[_builtins.str]:
        """
        Webhook payload format.
        """
        return pulumi.get(self, "format")

    @_builtins.property
    @pulumi.getter(name="includeAgentPrompt")
    def include_agent_prompt(self) -> Optional[_builtins.bool]:
        """
        Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to `true` when omitted.
        """
        return pulumi.get(self, "include_agent_prompt")

    @_builtins.property
    @pulumi.getter(name="installId")
    def install_id(self) -> Optional[_builtins.str]:
        """
        ID of the organization's Slack App or PagerDuty App installation, created by connecting the platform in the Logfire UI (Organization Settings > Connections). The installation must belong to the same organization, be active, and match the channel type.
        """
        return pulumi.get(self, "install_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[_builtins.str]:
        """
        PagerDuty account region (`us` or `eu`). When omitted, Logfire uses the US Events API endpoint. Only for `pagerduty` channels; a `pagerduty-integration` channel takes its region from the connected account.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="routingKey")
    def routing_key(self) -> Optional[_builtins.str]:
        """
        PagerDuty Events API v2 integration routing key. Only for `pagerduty` channels; `pagerduty-integration` channels resolve the key from the installation instead.
        """
        return pulumi.get(self, "routing_key")

    @_builtins.property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> Optional[_builtins.str]:
        """
        Logfire's ID (a UUID) for the PagerDuty service incidents are opened on, as approved for the installation when connecting PagerDuty. This is not PagerDuty's own service ID. Required for `pagerduty-integration` channels.
        """
        return pulumi.get(self, "service_id")

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[_builtins.str]:
        """
        Webhook URL endpoint.
        """
        return pulumi.get(self, "url")


