// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logfire.Inputs
{

    public sealed class ChannelConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("authKey")]
        private Input<string>? _authKey;

        /// <summary>
        /// Opsgenie API key.
        /// </summary>
        public Input<string>? AuthKey
        {
            get => _authKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _authKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Webhook payload format.
        /// </summary>
        [Input("format")]
        public Input<string>? Format { get; set; }

        /// <summary>
        /// Channel type (`Webhook` or `Opsgenie`).
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Webhook URL endpoint.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ChannelConfigGetArgs()
        {
        }
        public static new ChannelConfigGetArgs Empty => new ChannelConfigGetArgs();
    }
}
