name: Nightly Acceptance Tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: "47 5 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prerequisites:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/prerequisites.yml
    secrets: inherit
    with:
      default_branch: main
      is_pr: false
      is_automated: false

  build_provider:
    needs: prerequisites
    permissions:
      contents: read
    uses: ./.github/workflows/build_provider.yml
    secrets: inherit
    with:
      version: ${{ needs.prerequisites.outputs.version }}
      matrix: |
        {
          "platform": [
            {"os": "linux", "arch": "amd64"}
          ]
        }

  build_sdk:
    name: build_sdk
    needs: prerequisites
    permissions:
      contents: write
    uses: ./.github/workflows/build_sdk.yml
    secrets: inherit
    with:
      version: ${{ needs.prerequisites.outputs.version }}

  test:
    needs:
      - prerequisites
      - build_provider
      - build_sdk
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      version: ${{ needs.prerequisites.outputs.version }}
