// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Logfire alert.
 */
export class Alert extends pulumi.CustomResource {
    /**
     * Get an existing Alert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertState, opts?: pulumi.CustomResourceOptions): Alert {
        return new Alert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logfire:index/alert:Alert';

    /**
     * Returns true if the given object is an instance of Alert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Alert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Alert.__pulumiType;
    }

    /**
     * Whether the alert is active (defaults to true on creation).
     */
    declare public readonly active: pulumi.Output<boolean>;
    /**
     * Set of channel IDs to notify.
     */
    declare public readonly channelIds: pulumi.Output<string[]>;
    /**
     * Alert description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Evaluation frequency as Go duration
     */
    declare public readonly frequency: pulumi.Output<string>;
    /**
     * Alert name (unique per project).
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Notification rule. Must match API enum.
     */
    declare public readonly notifyWhen: pulumi.Output<string>;
    /**
     * Project ID (UUID) used for alert API paths.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * SQL / query string used by the alert.
     */
    declare public readonly query: pulumi.Output<string>;
    /**
     * Lookback window as Go duration
     */
    declare public readonly timeWindow: pulumi.Output<string>;
    /**
     * Provider-managed watermark (lateness tolerance) sent to the API.
     */
    declare public /*out*/ readonly watermark: pulumi.Output<string>;

    /**
     * Create a Alert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertArgs | AlertState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["channelIds"] = state?.channelIds;
            resourceInputs["description"] = state?.description;
            resourceInputs["frequency"] = state?.frequency;
            resourceInputs["name"] = state?.name;
            resourceInputs["notifyWhen"] = state?.notifyWhen;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["query"] = state?.query;
            resourceInputs["timeWindow"] = state?.timeWindow;
            resourceInputs["watermark"] = state?.watermark;
        } else {
            const args = argsOrState as AlertArgs | undefined;
            if (args?.channelIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelIds'");
            }
            if (args?.frequency === undefined && !opts.urn) {
                throw new Error("Missing required property 'frequency'");
            }
            if (args?.notifyWhen === undefined && !opts.urn) {
                throw new Error("Missing required property 'notifyWhen'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.query === undefined && !opts.urn) {
                throw new Error("Missing required property 'query'");
            }
            if (args?.timeWindow === undefined && !opts.urn) {
                throw new Error("Missing required property 'timeWindow'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["channelIds"] = args?.channelIds;
            resourceInputs["description"] = args?.description;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["name"] = args?.name;
            resourceInputs["notifyWhen"] = args?.notifyWhen;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["query"] = args?.query;
            resourceInputs["timeWindow"] = args?.timeWindow;
            resourceInputs["watermark"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Alert.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Alert resources.
 */
export interface AlertState {
    /**
     * Whether the alert is active (defaults to true on creation).
     */
    active?: pulumi.Input<boolean>;
    /**
     * Set of channel IDs to notify.
     */
    channelIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Alert description.
     */
    description?: pulumi.Input<string>;
    /**
     * Evaluation frequency as Go duration
     */
    frequency?: pulumi.Input<string>;
    /**
     * Alert name (unique per project).
     */
    name?: pulumi.Input<string>;
    /**
     * Notification rule. Must match API enum.
     */
    notifyWhen?: pulumi.Input<string>;
    /**
     * Project ID (UUID) used for alert API paths.
     */
    projectId?: pulumi.Input<string>;
    /**
     * SQL / query string used by the alert.
     */
    query?: pulumi.Input<string>;
    /**
     * Lookback window as Go duration
     */
    timeWindow?: pulumi.Input<string>;
    /**
     * Provider-managed watermark (lateness tolerance) sent to the API.
     */
    watermark?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Alert resource.
 */
export interface AlertArgs {
    /**
     * Whether the alert is active (defaults to true on creation).
     */
    active?: pulumi.Input<boolean>;
    /**
     * Set of channel IDs to notify.
     */
    channelIds: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Alert description.
     */
    description?: pulumi.Input<string>;
    /**
     * Evaluation frequency as Go duration
     */
    frequency: pulumi.Input<string>;
    /**
     * Alert name (unique per project).
     */
    name?: pulumi.Input<string>;
    /**
     * Notification rule. Must match API enum.
     */
    notifyWhen: pulumi.Input<string>;
    /**
     * Project ID (UUID) used for alert API paths.
     */
    projectId: pulumi.Input<string>;
    /**
     * SQL / query string used by the alert.
     */
    query: pulumi.Input<string>;
    /**
     * Lookback window as Go duration
     */
    timeWindow: pulumi.Input<string>;
}
