// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a Logfire API key. Write tokens (`project:write_otlp`), read tokens (`project:read_otlp`), gateway keys (`project:gateway_proxy`), and management keys are all API keys with different scopes. The new key can never exceed the provider credential's own grant: its scopes must be a subset of the provider `apiKey` scopes, so the provider key needs `organization:create_api_key` plus every scope it delegates.
 */
export class ApiKey extends pulumi.CustomResource {
    /**
     * Get an existing ApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApiKeyState, opts?: pulumi.CustomResourceOptions): ApiKey {
        return new ApiKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logfire:index/apiKey:ApiKey';

    /**
     * Returns true if the given object is an instance of ApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiKey.__pulumiType;
    }

    declare public /*out*/ readonly active: pulumi.Output<boolean>;
    /**
     * True for org-wide keys with no project scope.
     */
    declare public /*out*/ readonly allProjects: pulumi.Output<boolean>;
    /**
     * Timestamp when the key was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Display name of the user that created the key, when known.
     */
    declare public /*out*/ readonly createdByName: pulumi.Output<string>;
    /**
     * Free-form description. Can be updated in place; setting it to null clears it.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Optional RFC3339 expiration timestamp (for example `2026-12-31T23:59:59Z`). If omitted, the key does not expire. Changing it replaces the key: expiry cannot be updated in place (an expired key cannot be re-enabled; create a new key instead).
     */
    declare public readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * Gateway per-scope settings for keys with the `project:gateway_proxy` scope. Updatable in place. Removing the block clears every cap the key carries.
     */
    declare public readonly gateway: pulumi.Output<outputs.ApiKeyGateway | undefined>;
    /**
     * Display name for the key. Can be updated in place.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * UUID of the project the key is scoped to. Omit for an org-wide key. Changing the project replaces the key. Scopes `project:read_otlp`, `project:write_otlp`, and `project:gateway_proxy` require a project.
     */
    declare public readonly projectId: pulumi.Output<string | undefined>;
    /**
     * Name of the project the key is scoped to, if any.
     */
    declare public /*out*/ readonly projectName: pulumi.Output<string>;
    /**
     * OAuth scopes granted to the key (for example `project:write_otlp`). Changing scopes replaces the key: scopes cannot be updated in place.
     */
    declare public readonly scopes: pulumi.Output<string[]>;
    /**
     * The plaintext API key. Only returned on creation; never returned again by the API.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;

    /**
     * Create a ApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApiKeyArgs | ApiKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApiKeyState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["allProjects"] = state?.allProjects;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdByName"] = state?.createdByName;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["gateway"] = state?.gateway;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["projectName"] = state?.projectName;
            resourceInputs["scopes"] = state?.scopes;
            resourceInputs["token"] = state?.token;
        } else {
            const args = argsOrState as ApiKeyArgs | undefined;
            if (args?.scopes === undefined && !opts.urn) {
                throw new Error("Missing required property 'scopes'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["gateway"] = args?.gateway;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["active"] = undefined /*out*/;
            resourceInputs["allProjects"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdByName"] = undefined /*out*/;
            resourceInputs["projectName"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ApiKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ApiKey resources.
 */
export interface ApiKeyState {
    active?: pulumi.Input<boolean>;
    /**
     * True for org-wide keys with no project scope.
     */
    allProjects?: pulumi.Input<boolean>;
    /**
     * Timestamp when the key was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Display name of the user that created the key, when known.
     */
    createdByName?: pulumi.Input<string>;
    /**
     * Free-form description. Can be updated in place; setting it to null clears it.
     */
    description?: pulumi.Input<string>;
    /**
     * Optional RFC3339 expiration timestamp (for example `2026-12-31T23:59:59Z`). If omitted, the key does not expire. Changing it replaces the key: expiry cannot be updated in place (an expired key cannot be re-enabled; create a new key instead).
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Gateway per-scope settings for keys with the `project:gateway_proxy` scope. Updatable in place. Removing the block clears every cap the key carries.
     */
    gateway?: pulumi.Input<inputs.ApiKeyGateway>;
    /**
     * Display name for the key. Can be updated in place.
     */
    name?: pulumi.Input<string>;
    /**
     * UUID of the project the key is scoped to. Omit for an org-wide key. Changing the project replaces the key. Scopes `project:read_otlp`, `project:write_otlp`, and `project:gateway_proxy` require a project.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Name of the project the key is scoped to, if any.
     */
    projectName?: pulumi.Input<string>;
    /**
     * OAuth scopes granted to the key (for example `project:write_otlp`). Changing scopes replaces the key: scopes cannot be updated in place.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The plaintext API key. Only returned on creation; never returned again by the API.
     */
    token?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ApiKey resource.
 */
export interface ApiKeyArgs {
    /**
     * Free-form description. Can be updated in place; setting it to null clears it.
     */
    description?: pulumi.Input<string>;
    /**
     * Optional RFC3339 expiration timestamp (for example `2026-12-31T23:59:59Z`). If omitted, the key does not expire. Changing it replaces the key: expiry cannot be updated in place (an expired key cannot be re-enabled; create a new key instead).
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Gateway per-scope settings for keys with the `project:gateway_proxy` scope. Updatable in place. Removing the block clears every cap the key carries.
     */
    gateway?: pulumi.Input<inputs.ApiKeyGateway>;
    /**
     * Display name for the key. Can be updated in place.
     */
    name?: pulumi.Input<string>;
    /**
     * UUID of the project the key is scoped to. Omit for an org-wide key. Changing the project replaces the key. Scopes `project:read_otlp`, `project:write_otlp`, and `project:gateway_proxy` require a project.
     */
    projectId?: pulumi.Input<string>;
    /**
     * OAuth scopes granted to the key (for example `project:write_otlp`). Changing scopes replaces the key: scopes cannot be updated in place.
     */
    scopes: pulumi.Input<pulumi.Input<string>[]>;
}
