// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a project-scoped AI Gateway API key (`project:gateway_proxy` scope). Do not confuse this with `logfire.GatewayProvider`, which configures an upstream LLM provider credential. The provider credential needs `organization:create_api_key` plus `project:gateway_proxy` delegation.
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Import an existing gateway API key by its UUID. Key names are not unique
 *
 * across the organization, so the import is UUID-only. The UUID comes from the
 *
 * API key list endpoint (the API never returns the plaintext token again, so an
 *
 * import recovers the key without its token):
 *
 *   curl -s -H "Authorization: Bearer $LOGFIRE_API_KEY" \
 *
 *     "$LOGFIRE_BASE_URL/api/v1/api-keys/" | jq '.[] | {id, name}'
 *
 * ```sh
 * $ pulumi import logfire:index/gatewayApiKey:GatewayApiKey example' "9f9b2f9e-aaaa-bbbb-cccc-ddddeeeeffff"
 * ```
 */
export class GatewayApiKey extends pulumi.CustomResource {
    /**
     * Get an existing GatewayApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayApiKeyState, opts?: pulumi.CustomResourceOptions): GatewayApiKey {
        return new GatewayApiKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logfire:index/gatewayApiKey:GatewayApiKey';

    /**
     * Returns true if the given object is an instance of GatewayApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayApiKey.__pulumiType;
    }

    declare public /*out*/ readonly active: pulumi.Output<boolean>;
    /**
     * Whether gateway responses are cached. Null inherits the project default. Can be updated in place; setting it to null restores the default.
     */
    declare public readonly cacheEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Timestamp when the key was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Free-form description. Can be updated in place; setting it to null clears it.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Optional RFC3339 expiration timestamp (for example `2026-12-31T23:59:59Z`). If omitted, the key does not expire. Changing it replaces the key.
     */
    declare public readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * Display name for the key. Can be updated in place.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * UUID of the project the key proxies for. Gateway keys always require a project. Changing it replaces the key.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Name of the project the key proxies for.
     */
    declare public /*out*/ readonly projectName: pulumi.Output<string>;
    /**
     * Maximum gateway spend in whole US dollars per day. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    declare public readonly spendingLimitDaily: pulumi.Output<number | undefined>;
    /**
     * Maximum gateway spend in whole US dollars per month. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    declare public readonly spendingLimitMonthly: pulumi.Output<number | undefined>;
    /**
     * Maximum gateway spend in whole US dollars per lifetime. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    declare public readonly spendingLimitTotal: pulumi.Output<number | undefined>;
    /**
     * Maximum gateway spend in whole US dollars per week. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    declare public readonly spendingLimitWeekly: pulumi.Output<number | undefined>;
    /**
     * The plaintext gateway API key. Only returned on creation; never returned again by the API.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;

    /**
     * Create a GatewayApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayApiKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayApiKeyArgs | GatewayApiKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayApiKeyState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["cacheEnabled"] = state?.cacheEnabled;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["projectName"] = state?.projectName;
            resourceInputs["spendingLimitDaily"] = state?.spendingLimitDaily;
            resourceInputs["spendingLimitMonthly"] = state?.spendingLimitMonthly;
            resourceInputs["spendingLimitTotal"] = state?.spendingLimitTotal;
            resourceInputs["spendingLimitWeekly"] = state?.spendingLimitWeekly;
            resourceInputs["token"] = state?.token;
        } else {
            const args = argsOrState as GatewayApiKeyArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["cacheEnabled"] = args?.cacheEnabled;
            resourceInputs["description"] = args?.description;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["spendingLimitDaily"] = args?.spendingLimitDaily;
            resourceInputs["spendingLimitMonthly"] = args?.spendingLimitMonthly;
            resourceInputs["spendingLimitTotal"] = args?.spendingLimitTotal;
            resourceInputs["spendingLimitWeekly"] = args?.spendingLimitWeekly;
            resourceInputs["active"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["projectName"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GatewayApiKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GatewayApiKey resources.
 */
export interface GatewayApiKeyState {
    active?: pulumi.Input<boolean>;
    /**
     * Whether gateway responses are cached. Null inherits the project default. Can be updated in place; setting it to null restores the default.
     */
    cacheEnabled?: pulumi.Input<boolean>;
    /**
     * Timestamp when the key was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Free-form description. Can be updated in place; setting it to null clears it.
     */
    description?: pulumi.Input<string>;
    /**
     * Optional RFC3339 expiration timestamp (for example `2026-12-31T23:59:59Z`). If omitted, the key does not expire. Changing it replaces the key.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Display name for the key. Can be updated in place.
     */
    name?: pulumi.Input<string>;
    /**
     * UUID of the project the key proxies for. Gateway keys always require a project. Changing it replaces the key.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Name of the project the key proxies for.
     */
    projectName?: pulumi.Input<string>;
    /**
     * Maximum gateway spend in whole US dollars per day. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitDaily?: pulumi.Input<number>;
    /**
     * Maximum gateway spend in whole US dollars per month. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitMonthly?: pulumi.Input<number>;
    /**
     * Maximum gateway spend in whole US dollars per lifetime. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitTotal?: pulumi.Input<number>;
    /**
     * Maximum gateway spend in whole US dollars per week. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitWeekly?: pulumi.Input<number>;
    /**
     * The plaintext gateway API key. Only returned on creation; never returned again by the API.
     */
    token?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GatewayApiKey resource.
 */
export interface GatewayApiKeyArgs {
    /**
     * Whether gateway responses are cached. Null inherits the project default. Can be updated in place; setting it to null restores the default.
     */
    cacheEnabled?: pulumi.Input<boolean>;
    /**
     * Free-form description. Can be updated in place; setting it to null clears it.
     */
    description?: pulumi.Input<string>;
    /**
     * Optional RFC3339 expiration timestamp (for example `2026-12-31T23:59:59Z`). If omitted, the key does not expire. Changing it replaces the key.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Display name for the key. Can be updated in place.
     */
    name?: pulumi.Input<string>;
    /**
     * UUID of the project the key proxies for. Gateway keys always require a project. Changing it replaces the key.
     */
    projectId: pulumi.Input<string>;
    /**
     * Maximum gateway spend in whole US dollars per day. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitDaily?: pulumi.Input<number>;
    /**
     * Maximum gateway spend in whole US dollars per month. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitMonthly?: pulumi.Input<number>;
    /**
     * Maximum gateway spend in whole US dollars per lifetime. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitTotal?: pulumi.Input<number>;
    /**
     * Maximum gateway spend in whole US dollars per week. Null means no limit. Can be updated in place; setting it to null clears it.
     */
    spendingLimitWeekly?: pulumi.Input<number>;
}
