// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resolves a PagerDuty service approved through a Logfire connection to the IDs required by a `pagerduty-integration` channel. PagerDuty's external service ID is resolved to Logfire's internal installation and resource IDs. The provider API key requires the `organization:read_channel` scope.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as logfire from "@pydantic/pulumi-logfire";
 *
 * const onCall = logfire.getPagerdutyService({
 *     accountSubdomain: "acme",
 *     region: "us",
 *     pagerdutyServiceId: "PABC123",
 * });
 * const pagerdutyApp = new logfire.Channel("pagerdutyApp", {config: [{
 *     type: "pagerduty-integration",
 *     installId: onCall.then(onCall => onCall.installId),
 *     serviceId: onCall.then(onCall => onCall.serviceId),
 * }]});
 * ```
 */
export function getPagerdutyService(args: GetPagerdutyServiceArgs, opts?: pulumi.InvokeOptions): Promise<GetPagerdutyServiceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("logfire:index/getPagerdutyService:getPagerdutyService", {
        "accountSubdomain": args.accountSubdomain,
        "pagerdutyServiceId": args.pagerdutyServiceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getPagerdutyService.
 */
export interface GetPagerdutyServiceArgs {
    /**
     * PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
     */
    accountSubdomain: string;
    /**
     * PagerDuty's service ID, such as `PABC123`.
     */
    pagerdutyServiceId: string;
    /**
     * PagerDuty account region (`us` or `eu`). Defaults to `us`.
     */
    region?: string;
}

/**
 * A collection of values returned by getPagerdutyService.
 */
export interface GetPagerdutyServiceResult {
    /**
     * PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
     */
    readonly accountSubdomain: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Internal Logfire installation UUID for `logfire_channel.config.install_id`.
     */
    readonly installId: string;
    /**
     * PagerDuty's service ID, such as `PABC123`.
     */
    readonly pagerdutyServiceId: string;
    /**
     * PagerDuty account region (`us` or `eu`). Defaults to `us`.
     */
    readonly region: string;
    /**
     * Internal Logfire resource UUID for `logfire_channel.config.service_id`.
     */
    readonly serviceId: string;
    /**
     * PagerDuty service name.
     */
    readonly serviceName: string;
}
/**
 * Resolves a PagerDuty service approved through a Logfire connection to the IDs required by a `pagerduty-integration` channel. PagerDuty's external service ID is resolved to Logfire's internal installation and resource IDs. The provider API key requires the `organization:read_channel` scope.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as logfire from "@pydantic/pulumi-logfire";
 *
 * const onCall = logfire.getPagerdutyService({
 *     accountSubdomain: "acme",
 *     region: "us",
 *     pagerdutyServiceId: "PABC123",
 * });
 * const pagerdutyApp = new logfire.Channel("pagerdutyApp", {config: [{
 *     type: "pagerduty-integration",
 *     installId: onCall.then(onCall => onCall.installId),
 *     serviceId: onCall.then(onCall => onCall.serviceId),
 * }]});
 * ```
 */
export function getPagerdutyServiceOutput(args: GetPagerdutyServiceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPagerdutyServiceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("logfire:index/getPagerdutyService:getPagerdutyService", {
        "accountSubdomain": args.accountSubdomain,
        "pagerdutyServiceId": args.pagerdutyServiceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getPagerdutyService.
 */
export interface GetPagerdutyServiceOutputArgs {
    /**
     * PagerDuty account subdomain, such as `acme` from `acme.pagerduty.com`.
     */
    accountSubdomain: pulumi.Input<string>;
    /**
     * PagerDuty's service ID, such as `PABC123`.
     */
    pagerdutyServiceId: pulumi.Input<string>;
    /**
     * PagerDuty account region (`us` or `eu`). Defaults to `us`.
     */
    region?: pulumi.Input<string>;
}
