// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a Logfire SLO (Service Level Objective).
 *
 * > **Experimental:** this resource is backed by a Logfire API that is not yet stable. Its schema and behavior may change in backwards-incompatible ways in future releases. SLOs also require a Logfire plan that includes them.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as logfire from "@pydantic/pulumi-logfire";
 *
 * const exampleProject = new logfire.Project("exampleProject", {});
 * const alerts = new logfire.Channel("alerts", {config: [{
 *     type: "webhook",
 *     format: "auto",
 *     url: "https://hooks.example.com/alerts",
 * }]});
 * // An SLO has three burn-rate alerts: `fast` and `medium` (severity `page`)
 * // and `slow` (severity `ticket`). The provider writes each configured tier's
 * // channel assignments to its alert and reads them back, so a change made on
 * // the Logfire alerts page shows as drift in the next plan. A tier that is not
 * // configured keeps its channels.
 * const everyone = [{
 *     channel_id: alerts.id,
 * }];
 * const exampleSlo = new logfire.Slo("exampleSlo", {
 *     projectId: exampleProject.id,
 *     scopeValue: "payments-api",
 *     description: "Successful request ratio for the payments API",
 *     totalQuery: "parent_span_id IS NULL",
 *     badQuery: "otel_status_code = 'ERROR'",
 *     targetPercent: "99.9",
 *     rollingWindow: "30d",
 *     environments: ["prod"],
 *     alerts: {
 *         fast: {
 *             channelAssignments: everyone,
 *         },
 *         medium: {
 *             channelAssignments: everyone,
 *         },
 *         slow: {
 *             channelAssignments: everyone,
 *         },
 *     },
 * });
 * const config = new pulumi.Config();
 * const pagerdutyRoutingKey = config.require("pagerdutyRoutingKey");
 * // 2. Different channels per tier.
 * const pagerduty = new logfire.Channel("pagerduty", {config: [{
 *     type: "pagerduty",
 *     routingKey: pagerdutyRoutingKey,
 * }]});
 * const incidents = new logfire.Channel("incidents", {config: [{
 *     type: "webhook",
 *     format: "auto",
 *     url: "https://hooks.example.com/incidents",
 * }]});
 * const reliability = new logfire.Channel("reliability", {config: [{
 *     type: "webhook",
 *     format: "auto",
 *     url: "https://hooks.example.com/reliability",
 * }]});
 * const checkoutErrors = new logfire.Slo("checkoutErrors", {
 *     projectId: exampleProject.id,
 *     scopeValue: "checkout",
 *     totalQuery: "parent_span_id IS NULL",
 *     badQuery: "otel_status_code = 'ERROR'",
 *     targetPercent: "99.9",
 *     rollingWindow: "30d",
 *     alerts: {
 *         fast: {
 *             channelAssignments: [
 *                 {
 *                     channelId: pagerduty.id,
 *                 },
 *                 {
 *                     channelId: incidents.id,
 *                 },
 *             ],
 *         },
 *         medium: {
 *             channelAssignments: [{
 *                 channelId: incidents.id,
 *             }],
 *         },
 *         slow: {
 *             channelAssignments: [{
 *                 channelId: reliability.id,
 *             }],
 *         },
 *     },
 * });
 * // 3. Delivery schedules, shared with a normal alert. PagerDuty gets every
 * // fast and medium burn. The incidents channel gets them only during office
 * // hours, and the reliability channel gets slow burns during office hours. A
 * // normal alert reuses the same configuration, because both resources use the
 * // same assignment type.
 * const officeHours = new logfire.Schedule("officeHours", {
 *     label: "Office hours",
 *     timezone: "Europe/London",
 *     windows: [{
 *         days: [
 *             1,
 *             2,
 *             3,
 *             4,
 *             5,
 *         ],
 *         start_time: "09:00",
 *         end_time: "18:00",
 *     }],
 * });
 * const oncall = [
 *     {
 *         channel_id: pagerduty.id,
 *     },
 *     {
 *         channel_id: incidents.id,
 *         schedule_id: officeHours.id,
 *     },
 * ];
 * const checkout = new logfire.Slo("checkout", {
 *     projectId: exampleProject.id,
 *     scopeValue: "checkout",
 *     totalQuery: "parent_span_id IS NULL",
 *     badQuery: "otel_status_code = 'ERROR'",
 *     targetPercent: "99.9",
 *     rollingWindow: "30d",
 *     alerts: {
 *         fast: {
 *             channelAssignments: oncall,
 *         },
 *         medium: {
 *             channelAssignments: oncall,
 *         },
 *         slow: {
 *             channelAssignments: [{
 *                 channelId: reliability.id,
 *                 scheduleId: officeHours.id,
 *             }],
 *         },
 *     },
 * });
 * const paymentErrors = new logfire.Alert("paymentErrors", {
 *     projectId: exampleProject.id,
 *     query: "select trace_id from records where span_name = 'payment failed'",
 *     timeWindow: "5m",
 *     frequency: "1m",
 *     notifyWhen: "has_matches",
 *     channelAssignments: oncall,
 * });
 * // A histogram-threshold metric SLI: "95% of queue-latency observations under
 * // 60s". Uses `threshold` + `comparison` instead of `bad_query`, and requires
 * // `source = "metrics"`. It configures no tier, so the provider leaves the
 * // channels of its alerts as they are.
 * const queueLatency = new logfire.Slo("queueLatency", {
 *     projectId: exampleProject.id,
 *     scopeValue: "ingest",
 *     source: "metrics",
 *     metricAggregation: "histogram_threshold",
 *     totalQuery: "metric_name = 'queue.latency'",
 *     threshold: "60000",
 *     comparison: "less_than",
 *     targetPercent: "95",
 *     rollingWindow: "30d",
 * });
 * ```
 *
 * ## Import
 *
 * In Terraform v1.5.0 and later, the `import` block can be used with the `id` attribute, for example:
 *
 * terraform
 *
 * import {
 *
 *   to = logfire_slo.example
 *
 *   id = "example-project/payments-availability"
 *
 * }
 *
 * The `pulumi import` command can be used, for example:
 *
 * Import by project name and SLO name.
 *
 * ```sh
 * $ pulumi import logfire:index/slo:Slo example "example-project/payments-availability"
 * ```
 */
export class Slo extends pulumi.CustomResource {
    /**
     * Get an existing Slo resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SloState, opts?: pulumi.CustomResourceOptions): Slo {
        return new Slo(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logfire:index/slo:Slo';

    /**
     * Returns true if the given object is an instance of Slo.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Slo {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Slo.__pulumiType;
    }

    declare public readonly alerts: pulumi.Output<outputs.SloAlerts>;
    /**
     * SQL boolean expression selecting the bad events counted by the SLO. Required for every mode except `metricAggregation = "histogramThreshold"`, which uses `threshold` and `comparison` instead.
     */
    declare public readonly badQuery: pulumi.Output<string | undefined>;
    /**
     * For `metricAggregation = "histogramThreshold"`: the good side of the `threshold`. `lessThan` (good is below the threshold, the latency case) or `greaterThan`. Required for that mode, and must be omitted otherwise.
     */
    declare public readonly comparison: pulumi.Output<string | undefined>;
    /**
     * SLO description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Deployment environments the SLO is scoped to. Omit to cover all environments.
     */
    declare public readonly environments: pulumi.Output<string[] | undefined>;
    /**
     * How a `metrics` SLO aggregates its SLI: `additive` (sum of scalar values, for delta-count metrics), `gaugeFraction` (fraction of samples meeting the condition, for gauges), `counterRate` (sum of per-series increases, for cumulative counters), or `histogramThreshold` (fraction of histogram observations past a threshold; uses `threshold` and `comparison` instead of `badQuery`, and requires `source = "metrics"`). Ignored when `source = "records"`. Defaults to `additive`.
     */
    declare public readonly metricAggregation: pulumi.Output<string>;
    /**
     * SLO name (unique per project).
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Project ID (UUID) used for SLO API paths.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Rolling evaluation window as a duration string (e.g. `"24h"`, `"30d"`). Must be between 1h and 90d. The API enforces a lower effective cap: the window cannot exceed your subscription plan's maximum SLO window, nor the project's data retention for the SLO source (`records` or `metrics`) — a longer window would compute against missing data. Requests over either cap are rejected with a validation error.
     */
    declare public readonly rollingWindow: pulumi.Output<string>;
    /**
     * What the SLO is anchored to: a service (`service`) or an LLM provider (`provider`). Defaults to `service`. Changing it forces a new SLO.
     */
    declare public readonly scopeKind: pulumi.Output<string>;
    /**
     * The service name (`scopeKind = "service"`) or provider slug like `openai` (`scopeKind = "provider"`). Changing it forces a new SLO.
     */
    declare public readonly scopeValue: pulumi.Output<string>;
    /**
     * Whether the SLO ratio is computed over span events (`records`) or metric values (`metrics`). Defaults to `records`.
     */
    declare public readonly source: pulumi.Output<string>;
    /**
     * Target percentage as a decimal string, exclusively between 0 and 100 (e.g. `"99.9"`).
     */
    declare public readonly targetPercent: pulumi.Output<string>;
    /**
     * For `metricAggregation = "histogramThreshold"`: the cutoff in the metric's native unit, as a decimal string (e.g. `"60000"` on a `_ms` latency metric). Required for that mode, and must be omitted otherwise.
     */
    declare public readonly threshold: pulumi.Output<string | undefined>;
    /**
     * SQL boolean expression selecting all events counted by the SLO.
     */
    declare public readonly totalQuery: pulumi.Output<string>;

    /**
     * Create a Slo resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SloArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SloArgs | SloState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SloState | undefined;
            resourceInputs["alerts"] = state?.alerts;
            resourceInputs["badQuery"] = state?.badQuery;
            resourceInputs["comparison"] = state?.comparison;
            resourceInputs["description"] = state?.description;
            resourceInputs["environments"] = state?.environments;
            resourceInputs["metricAggregation"] = state?.metricAggregation;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["rollingWindow"] = state?.rollingWindow;
            resourceInputs["scopeKind"] = state?.scopeKind;
            resourceInputs["scopeValue"] = state?.scopeValue;
            resourceInputs["source"] = state?.source;
            resourceInputs["targetPercent"] = state?.targetPercent;
            resourceInputs["threshold"] = state?.threshold;
            resourceInputs["totalQuery"] = state?.totalQuery;
        } else {
            const args = argsOrState as SloArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.rollingWindow === undefined && !opts.urn) {
                throw new Error("Missing required property 'rollingWindow'");
            }
            if (args?.scopeValue === undefined && !opts.urn) {
                throw new Error("Missing required property 'scopeValue'");
            }
            if (args?.targetPercent === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetPercent'");
            }
            if (args?.totalQuery === undefined && !opts.urn) {
                throw new Error("Missing required property 'totalQuery'");
            }
            resourceInputs["alerts"] = args?.alerts;
            resourceInputs["badQuery"] = args?.badQuery;
            resourceInputs["comparison"] = args?.comparison;
            resourceInputs["description"] = args?.description;
            resourceInputs["environments"] = args?.environments;
            resourceInputs["metricAggregation"] = args?.metricAggregation;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["rollingWindow"] = args?.rollingWindow;
            resourceInputs["scopeKind"] = args?.scopeKind;
            resourceInputs["scopeValue"] = args?.scopeValue;
            resourceInputs["source"] = args?.source;
            resourceInputs["targetPercent"] = args?.targetPercent;
            resourceInputs["threshold"] = args?.threshold;
            resourceInputs["totalQuery"] = args?.totalQuery;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Slo.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Slo resources.
 */
export interface SloState {
    alerts?: pulumi.Input<inputs.SloAlerts>;
    /**
     * SQL boolean expression selecting the bad events counted by the SLO. Required for every mode except `metricAggregation = "histogramThreshold"`, which uses `threshold` and `comparison` instead.
     */
    badQuery?: pulumi.Input<string>;
    /**
     * For `metricAggregation = "histogramThreshold"`: the good side of the `threshold`. `lessThan` (good is below the threshold, the latency case) or `greaterThan`. Required for that mode, and must be omitted otherwise.
     */
    comparison?: pulumi.Input<string>;
    /**
     * SLO description.
     */
    description?: pulumi.Input<string>;
    /**
     * Deployment environments the SLO is scoped to. Omit to cover all environments.
     */
    environments?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * How a `metrics` SLO aggregates its SLI: `additive` (sum of scalar values, for delta-count metrics), `gaugeFraction` (fraction of samples meeting the condition, for gauges), `counterRate` (sum of per-series increases, for cumulative counters), or `histogramThreshold` (fraction of histogram observations past a threshold; uses `threshold` and `comparison` instead of `badQuery`, and requires `source = "metrics"`). Ignored when `source = "records"`. Defaults to `additive`.
     */
    metricAggregation?: pulumi.Input<string>;
    /**
     * SLO name (unique per project).
     */
    name?: pulumi.Input<string>;
    /**
     * Project ID (UUID) used for SLO API paths.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Rolling evaluation window as a duration string (e.g. `"24h"`, `"30d"`). Must be between 1h and 90d. The API enforces a lower effective cap: the window cannot exceed your subscription plan's maximum SLO window, nor the project's data retention for the SLO source (`records` or `metrics`) — a longer window would compute against missing data. Requests over either cap are rejected with a validation error.
     */
    rollingWindow?: pulumi.Input<string>;
    /**
     * What the SLO is anchored to: a service (`service`) or an LLM provider (`provider`). Defaults to `service`. Changing it forces a new SLO.
     */
    scopeKind?: pulumi.Input<string>;
    /**
     * The service name (`scopeKind = "service"`) or provider slug like `openai` (`scopeKind = "provider"`). Changing it forces a new SLO.
     */
    scopeValue?: pulumi.Input<string>;
    /**
     * Whether the SLO ratio is computed over span events (`records`) or metric values (`metrics`). Defaults to `records`.
     */
    source?: pulumi.Input<string>;
    /**
     * Target percentage as a decimal string, exclusively between 0 and 100 (e.g. `"99.9"`).
     */
    targetPercent?: pulumi.Input<string>;
    /**
     * For `metricAggregation = "histogramThreshold"`: the cutoff in the metric's native unit, as a decimal string (e.g. `"60000"` on a `_ms` latency metric). Required for that mode, and must be omitted otherwise.
     */
    threshold?: pulumi.Input<string>;
    /**
     * SQL boolean expression selecting all events counted by the SLO.
     */
    totalQuery?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Slo resource.
 */
export interface SloArgs {
    alerts?: pulumi.Input<inputs.SloAlerts>;
    /**
     * SQL boolean expression selecting the bad events counted by the SLO. Required for every mode except `metricAggregation = "histogramThreshold"`, which uses `threshold` and `comparison` instead.
     */
    badQuery?: pulumi.Input<string>;
    /**
     * For `metricAggregation = "histogramThreshold"`: the good side of the `threshold`. `lessThan` (good is below the threshold, the latency case) or `greaterThan`. Required for that mode, and must be omitted otherwise.
     */
    comparison?: pulumi.Input<string>;
    /**
     * SLO description.
     */
    description?: pulumi.Input<string>;
    /**
     * Deployment environments the SLO is scoped to. Omit to cover all environments.
     */
    environments?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * How a `metrics` SLO aggregates its SLI: `additive` (sum of scalar values, for delta-count metrics), `gaugeFraction` (fraction of samples meeting the condition, for gauges), `counterRate` (sum of per-series increases, for cumulative counters), or `histogramThreshold` (fraction of histogram observations past a threshold; uses `threshold` and `comparison` instead of `badQuery`, and requires `source = "metrics"`). Ignored when `source = "records"`. Defaults to `additive`.
     */
    metricAggregation?: pulumi.Input<string>;
    /**
     * SLO name (unique per project).
     */
    name?: pulumi.Input<string>;
    /**
     * Project ID (UUID) used for SLO API paths.
     */
    projectId: pulumi.Input<string>;
    /**
     * Rolling evaluation window as a duration string (e.g. `"24h"`, `"30d"`). Must be between 1h and 90d. The API enforces a lower effective cap: the window cannot exceed your subscription plan's maximum SLO window, nor the project's data retention for the SLO source (`records` or `metrics`) — a longer window would compute against missing data. Requests over either cap are rejected with a validation error.
     */
    rollingWindow: pulumi.Input<string>;
    /**
     * What the SLO is anchored to: a service (`service`) or an LLM provider (`provider`). Defaults to `service`. Changing it forces a new SLO.
     */
    scopeKind?: pulumi.Input<string>;
    /**
     * The service name (`scopeKind = "service"`) or provider slug like `openai` (`scopeKind = "provider"`). Changing it forces a new SLO.
     */
    scopeValue: pulumi.Input<string>;
    /**
     * Whether the SLO ratio is computed over span events (`records`) or metric values (`metrics`). Defaults to `records`.
     */
    source?: pulumi.Input<string>;
    /**
     * Target percentage as a decimal string, exclusively between 0 and 100 (e.g. `"99.9"`).
     */
    targetPercent: pulumi.Input<string>;
    /**
     * For `metricAggregation = "histogramThreshold"`: the cutoff in the metric's native unit, as a decimal string (e.g. `"60000"` on a `_ms` latency metric). Required for that mode, and must be omitted otherwise.
     */
    threshold?: pulumi.Input<string>;
    /**
     * SQL boolean expression selecting all events counted by the SLO.
     */
    totalQuery: pulumi.Input<string>;
}
