// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Logfire write token.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as logfire from "@pydantic/pulumi-logfire";
 *
 * const exampleProject = new logfire.Project("exampleProject", {});
 * const exampleWriteToken = new logfire.WriteToken("exampleWriteToken", {
 *     projectId: exampleProject.id,
 *     expiresAt: "2099-12-31T23:59:59Z",
 * });
 * ```
 */
export class WriteToken extends pulumi.CustomResource {
    /**
     * Get an existing WriteToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WriteTokenState, opts?: pulumi.CustomResourceOptions): WriteToken {
        return new WriteToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logfire:index/writeToken:WriteToken';

    /**
     * Returns true if the given object is an instance of WriteToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WriteToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WriteToken.__pulumiType;
    }

    /**
     * Timestamp when the token was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Display name of the user that created the token.
     */
    declare public /*out*/ readonly createdByName: pulumi.Output<string>;
    /**
     * Description is fixed to "Created by Public API" for provider-managed tokens.
     */
    declare public /*out*/ readonly description: pulumi.Output<string>;
    /**
     * Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
     */
    declare public readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * UUID of the project that owns the token.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Name of the project that owns the token.
     */
    declare public /*out*/ readonly projectName: pulumi.Output<string>;
    /**
     * The generated write token. Only returned on creation.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * Prefix of the generated write token.
     */
    declare public /*out*/ readonly tokenPrefix: pulumi.Output<string>;

    /**
     * Create a WriteToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WriteTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WriteTokenArgs | WriteTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WriteTokenState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdByName"] = state?.createdByName;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["projectName"] = state?.projectName;
            resourceInputs["token"] = state?.token;
            resourceInputs["tokenPrefix"] = state?.tokenPrefix;
        } else {
            const args = argsOrState as WriteTokenArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdByName"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["projectName"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenPrefix"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(WriteToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WriteToken resources.
 */
export interface WriteTokenState {
    /**
     * Timestamp when the token was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Display name of the user that created the token.
     */
    createdByName?: pulumi.Input<string>;
    /**
     * Description is fixed to "Created by Public API" for provider-managed tokens.
     */
    description?: pulumi.Input<string>;
    /**
     * Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * UUID of the project that owns the token.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Name of the project that owns the token.
     */
    projectName?: pulumi.Input<string>;
    /**
     * The generated write token. Only returned on creation.
     */
    token?: pulumi.Input<string>;
    /**
     * Prefix of the generated write token.
     */
    tokenPrefix?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a WriteToken resource.
 */
export interface WriteTokenArgs {
    /**
     * Optional RFC3339 expiration timestamp for the token (for example `2026-12-31T23:59:59Z`). If omitted, the token does not expire.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * UUID of the project that owns the token.
     */
    projectId: pulumi.Input<string>;
}
